### ISSUE TITLE
Crash upon saving or opening file under certain conditions

### ISSUE THREAD

**Issue by haringsrob** [atom/atom#9621]
When, in a git initialized folder, I save a certain file multiple times, then it crashes on opening until I commit it. Then this reoccurs doing the same steps.

**Reproduction Steps:**
1. Open a git project
2. Open a file with a non default extension (ex template.theme)
3. Set it to php
4. Save the file
5. Edit the file
6. Save the file again

**Expected behavior:**

File get saved.

**Observed behavior:**

Atom crashes. And keeps crashing on open.

**Screenshots and GIFs**

![screen shot 2015-11-16 at 12 27 17](https://cloud.githubusercontent.com/assets/866743/11180736/6efea404-8c5d-11e5-93e5-259696d91032.png)

**Atom version:** 1.2.0
**OS and version:** OS X 10.11.1

**Installed packages:**

None, created a clean install

**Additional information:**
- Problem can be reproduced in safe mode: Yes
- Problem started happening recently, didn't happen in an older version of Atom: Yes
- Problem can be reliably reproduced, doesn't happen randomly: No
- Problem happens with all files and projects, not only some files or projects: No

**Comment by haringsrob** [comment]
If someone can tell me how I can see the debug logs, I could try and debug it myself.

**Comment by izuzak** [comment]
Thanks for the report, @haringsrob! It seems that you used the [template from the contributing guide](https://github.com/atom/atom/blob/master/CONTRIBUTING.md#template-for-submitting-bug-reports) -- that's great! :zap: If you scroll a bit up from that template, you should see a section which has a line that tells you [how to get the crash report on OSX](https://github.com/atom/atom/blob/master/CONTRIBUTING.md#how-do-i-submit-a-good-bug-report):

_"If you're reporting that Atom crashed, include a crash report with a stack trace from the operating system. On OSX, the crash report will be available in Console.app under "Diagnostic and usage information" > "User diagnostic reports". Include the crash report in the issue in a code block, a file attachment, or put it in a gist and provide link to that gist."_

**Comment by haringsrob** [comment]
Hi,

Here it is: 
https://gist.github.com/haringsrob/cc2626d965242385e34b

Regards,

**Comment by izuzak** [comment]
Thanks, @haringsrob!

@zcbenz -- any ideas on this crash?
