### ISSUE TITLE
Searching with a regex in the whole project doesn't always work as expected

### ISSUE THREAD

**Issue by Glennvd** [atom/atom#9623]
Ran into this issue today while cleaning up some code, I was trying to get rid of some extra linebreaks and searched for `\n\n\n`. When I do this on a single page the results come back as expected. When I do this on the whole project it only finds 1 or 0 matches while there should be multiple.

**Comment by izuzak** [comment]
Thanks for the report, @Glennvd. I think this is a duplicate of https://github.com/atom/find-and-replace/issues/218 so I'm going to close this in favor of that issue. If I misunderstood, please let me know. :v:
