### ISSUE TITLE
Strange marker behavior when scrolling with soft wrap enabled

### ISSUE THREAD

**Issue by izuzak** [atom/atom#9628]
Just noticed the following behavior on latest master (1.4.0-dev-2696f49) with spellcheck lines and find-and-replace selections:

![oh-spellchecker](https://cloud.githubusercontent.com/assets/38924/11184315/22439416-8c77-11e5-8ad0-29256988c9da.gif)

![oh-markers](https://cloud.githubusercontent.com/assets/38924/11184314/22324f80-8c77-11e5-8f8c-01edc378723f.gif)

Notice how the markers somehow translate from line to line as the top edge of the editor scrolls over the line with the marker (I'm only _guessing_ this is marker related since it can be reproduced with both spellcheck lines and find-and-replace selections, I haven't investigated this further).

I was able to reproduce this with a bunch of lorem ipsum snippets wrapped to 80 chars (notice the top line which has double spellcheck lines):

<img width="887" alt="screen shot 2015-11-16 at 15 32 35" src="https://cloud.githubusercontent.com/assets/38924/11184439/dc03a0ee-8c77-11e5-83b5-1340993cdc8c.png">

cc @nathansobo @as-cii for more :eyes: Also, not sure if this is related, but https://github.com/atom/atom/issues/8007 has similar keywords as this.

**Comment by nathansobo** [comment]
Taking a look now. @izuzak have you been able to reproduce on beta at all?

**Comment by abe33** [comment]
@nathansobo No reproduction on beta for me, only on master.

**Comment by izuzak** [comment]
> No reproduction on beta for me, only on master.

@abe Hmm, strange -- I've been able to reproduce this on beta as well, but not on stable. @nathansobo -- the easiest way to reproduce this is to open a new tab, enable soft wrapping, paste a bunch of lorem ipsum text (so that you can scroll), and then slowly scroll down. You'll see how the spellcheck lines duplicate on the line which the top edge of the screen is over.

**Comment by abe33** [comment]
@izuzak Oh s***, my beta branch was out of date, rebuilding now.

**Comment by abe33** [comment]
Right, I can reproduce that on beta as well. My bad...

**Comment by izuzak** [comment]
@nathansobo I can still reproduce this on latest master. Are you sure this was fixed by 8da44c4?

**Comment by nathansobo** [comment]
@izuzak Ugh, it got lost in the merge of `beta` into `master`. Fixed it again, hopefully for good this time.

**Comment by izuzak** [comment]
Yep, looks good now -- double :zap: :zap: for fixing this two times, @nathansobo!
