### ISSUE TITLE
File path copied with Linux/Unix style on Windows

### ISSUE THREAD

**Issue by niall83** [atom/atom#9632]
In the status bar at the bottom of the editor window it displays the path for the currently open file e.g. C:\test\test.txt.

When I click on it, in order to copy the path to the clip board it copies with a Linux/Unix style path even though I'm using Windows:
/test/test.txt

![image](https://cloud.githubusercontent.com/assets/15875346/11189156/949f974e-8c86-11e5-897f-b6cdff20624a.png)

**Comment by izuzak** [comment]
This issue was moved to atom/status-bar#113

**Comment by ash84** [comment]
Is there a way to have an option to copy in either Windows or unix style on Windows 10
