### ISSUE TITLE
Undo/Redo stack cleared on save when the file is changed before save

### ISSUE THREAD

**Issue by diegopso** [atom/atom#9637]
Hi,

I used the Undo feature to go back into a stage that I desire to check something in my code. I went back something like 50 times. I checked watherever I was looking for and then I was ready to go back to the last stage by using Ctrl+Y. Unfortunatelly, the Redo feature only worked something like 20 times, and I lost some code.

Did anyone have the same issue?

P.S.: Hope this is the right place to post about it...

**Comment by maxbrunsfeld** [comment]
Yeah this is a fine place to post this. Can you reproduce this reliably? If so, could you post some exact steps?

**Comment by diegopso** [comment]
I think I know exactly what I did, and probably the cause of ma issue. So, the steps are:

1. Opened a new file and saved it (foo.txt)
2. Performed 100 actions (just type 'a' in 100 diferent lines)
3. Ctrl+Z 50 times
4. Ctrl+S (to save, and in my case test the changes in the file)
5. Try to Ctrl+Y

In the step 5 I got three situations:

* The Ctrl+Y works perfectly
* The Ctrl+Y didnt work at all
* The Ctrl+Y worked a few times

One of the times I have saved the file I realized that a new line was added to it before saving. This was when the Redo didnt work at all.

**Comment by Ben3eeE** [comment]
This might be because the `whitespace` core package inserts a newline before saving, clearing the redo stack. I am blaming the `whitespace` package specifically because you mention new lines in the end of the file. Any package that changes the file before saving would cause this. There is a relevant discussion here: https://github.com/atom/whitespace/issues/101
As for ctrl-y only working a few times this might be because in the middle of undoing you save the file clearing the redo stack up to that point and then undo some more filling up the redo stack again.

**Comment by lee-dohm** [comment]
I'm going to follow up with the team on this. That the redo state is cleared when the file is changed is intentional and we may not pursue fixing this in the near term.

**Comment by Ben3eeE** [comment]
@lee-dohm https://github.com/atom/atom/issues/7572 mentions redo not working after saving and might be a duplicate.
And https://github.com/atom/atom/issues/7917 is an existing relevant (but maybe not duplicte) enhancement issue discussing vim like branch undo.

**Comment by dpetraz** [comment]
anyone else still having this problem? My redo history automatically clears upon saving the file.

**Comment by RoosDaniel** [comment]
@dpetraz same for me. Stumbled upon this issue when searching for a fix. @lee-dohm any updates?

**Comment by lee-dohm** [comment]
@RoosDaniel No, there aren't any updates. This issue was closed months ago. I also just tested it and can't reproduce the problem. If you're running into a reproducible bug, please open a new issue with detailed steps to reproduce the problem and completely fill out the template.
