### ISSUE TITLE
Example running initializing a single text document

### ISSUE THREAD

**Issue by matthewmueller** [atom/atom#9639]
Atom has the most sophisticated text editor created in JS that I've seen, compared to other open source alternatives. 

I was wondering if there's any examples or code on just initializing a single text document, without the window panes, tab menu, etc. 

I'd like to use it as a better markdown editor :-)

**Comment by benogle** [comment]
The text editor is currently pretty integrated into the atom codebase. You could attempt to pull it out. We would like to at some point, but it isnt a high poriority at this time.

**Comment by matthewmueller** [comment]
Oh okay cool. Do you have any tests or examples or starting points I could
check out?

**Comment by benogle** [comment]
I dont, sorry. You'll need to pull out the [TextEditor](https://github.com/atom/atom/blob/master/src/text-editor.coffee), [TextEditorComponent](https://github.com/atom/atom/blob/master/src/text-editor-component.coffee), and all their dependencies. Note that there are probably dragons.

**Comment by benogle** [comment]
Closing this as answered. Sorry I dont have a more worn path for you.

**Comment by matthewmueller** [comment]
no worries, appreciate the links!
