### ISSUE TITLE
Provide a method to get structured stacktrace from error.

### ISSUE THREAD

**Issue by scv119** [atom/atom#9641]
Atom provided a way to get raw stacktrace in [error.getRawStack](https://github.com/atom/atom/blob/6e8184658090b223e9eadcdef4bd39479a30e004/src/compile-cache.js#L171) and tries to prevent further modification of [Error.prepareStackTrace](https://github.com/atom/atom/blob/6e8184658090b223e9eadcdef4bd39479a30e004/src/compile-cache.js#L165). 

However, this doesn't work  if we run following:
```
const error = new Error();
error.stack;
error.getRawStack();
> "Error
    at <anonymous>:2:15
    at Object.InjectedScript._evaluateOn (<anonymous>:904:140)
    at Object.InjectedScript._evaluateAndWrap (<anonymous>:837:34)
    at Object.InjectedScript.evaluate (<anonymous>:693:21)"
```
Whereas Nuclide need this structured stack information to categorize/track errors by [customizing Error.prepareStackTrace](https://github.com/facebook/nuclide/blob/master/pkg/nuclide/logging/lib/stacktrace.js#L30), which had caused problems describe [here] (https://github.com/atom/grim/commit/8807010397e64f499b6815090d7b575aaf4a27c3#diff-dd248f5f751e9429ed611987b50f19b6R48), and https://github.com/facebook/nuclide/issues/246 .

For now, I could manually set `Error.prototype.getRawStack = null;` in our customization so that atom/grim will fallback to it's another implementation of [getRawStack](https://github.com/atom/grim/blob/master/src/grim.coffee#L80). 
But we need to fix the bug of error.getRawStack() so that Nuclide don't need to customize the stacktraces.

cc @nathansobo  @bolinfest

**Comment by nathansobo** [comment]
@scv119 Are you still doing `Object.defineProperty(Error, 'prepareStackTrace')` and overwriting that property? If so, `getRawStack` won't work.

**Comment by nathansobo** [comment]
Can you articulate to me exactly why you need to assign prepare stack trace, and if there's some API we could offer you that gave you the functionality you need without breaking our usage of it? We currently source-map stack traces in our version of `prepareStackTrace`, and having that overridden will cause problems. Are you actually formatting the stack traces for users to view, or could you call a method like `getRawStack` in certain places in your code to get access to the raw trace on an as-needed basis?

**Comment by scv119** [comment]
yeah @nathansobo. Internally (in Facebook) we collect every error in Nuclide and categorize them to keep track of Nuclide quality. To get a resonable categorization result, we customize prepareStackTrace so we could get access to structured information in `raw stacks`. That's said, if Atom provided a way to access the `raw stacktraces` for every error could meet our need.

**Comment by nathansobo** [comment]
@scv119 Pretty sure if you stop overriding `Error.prepareStackTrace`, that the existing `Error.prototype.getRawStack` method should work. Could you try that?

**Comment by scv119** [comment]
@nathansobo Yes, but there is a bug with `Error.prototype.getRawStack` as following:
```
const error = new Error();
error.stack;
error.getRawStack();
> "Error
    at <anonymous>:2:15
    at Object.InjectedScript._evaluateOn (<anonymous>:904:140)
    at Object.InjectedScript._evaluateAndWrap (<anonymous>:837:34)
    at Object.InjectedScript.evaluate (<anonymous>:693:21)"
```

**Comment by nathansobo** [comment]
I'm not sure what's going on in the dev-tools console, but I see a similar error. But if you run the `Application: Open Your Init Script` command and put this in your init script, then reload, it should work.

```js
e = new Error(
console.log(e.getRawStack())
```

Can you try using it in your actual code (not from the console) with your `prepareStackTrace` override disabled?

**Comment by scv119** [comment]
@nathansobo  yes, I tried that and still reproduce this bug. I believe this is caused by the implementation of [ getRawStack() ](https://github.com/atom/atom/blob/6e8184658090b223e9eadcdef4bd39479a30e004/src/compile-cache.js#L171-L176) function. 

```
Error.prototype.getRawStack = function () { // eslint-disable-line no-extend-native
  prepareStackTrace = getRawStack
  var result = this.stack 
  // For efficiency stack traces are not formatted when they are captured but on demand, 
  // the first time  the stack property is accessed. 
  // This is the cause of the bug.
  prepareStackTrace = sourceMapPrepareStackTrace
  return result
}
```
[Customizing stack traces](https://chromium.googlesource.com/v8/v8/+/master/docs/javascript_stack_trace_api.md#Customizing-stack-traces)

**Comment by nathansobo** [comment]
Can you open a pull request with a version that works for you? That way I can just see explicitly what you're talking about.

**Comment by scv119** [comment]
Sure, will send a PR.

**Comment by scv119** [comment]
https://github.com/atom/atom/pull/9772
