### ISSUE TITLE
Binary packages for 1.2.1 release are REALLY missing - with screenshot

### ISSUE THREAD

**Issue by alanfranz** [atom/atom#9647]
Hello,
I'm re-opening a ticket since #9645 was closed before I could answer.
I don't know what happened, but I can confirm there're no downloadable packages for 1.2.1. I DID wait a few days before opening the ticket because I had already noticed that the release files are attached AFTER the release is created.

![screenshot from 2015-11-17 11 28 27](https://cloud.githubusercontent.com/assets/230827/11208976/8ec1bb3e-8d1e-11e5-885f-0b6cec5681c3.png)

I don't know what you see there in the #9645 screenshot, but maybe the "draft" indication means something like "people working for GitHub/Atom can access this release, but others don't"? Have you tried accessing the releases page from an incognito window?

**Comment by abe33** [comment]
You could still reply in #9645 and ask me to reopen the issue instead of creating a new one though.

Actually you're right, the binaries are only available to owners and collaborators, and otoh it makes sense for a release in a draft state to not be made available to everyone, since there's probably a lot of things that still may be somewhat broken and we probably don't want these to get installed by users in the large before it have been properly reviewed internally.

**Comment by alanfranz** [comment]
I apologize for the double ticketing issue. Unluckily, there seems to be no
One Size Fits All "right answer" - in many FOSS I open tickets for, there
is no response after ticket is closed, and a new one must to opened to
really gather attention.

About the specific issue: what does it mean the release is in a "draft"
state? And how would people from outside know?
In fact, I can see that the webupd8 team, which rebuilds and repackages
Atom, has already pushed an 1.2.1 binary build on their PPA:
https://launchpad.net/~webupd8team/+archive/ubuntu/atom/

I'm the creator of the
https://github.com/alanfranz/atom-text-editor-repository , an apt and yum
mirror for original atom packages, and I can assure you it's the first time
it happens - usually release packages are in place within about an hour of
the original tagging - at least for full. non-beta releases.

If it's not a proper release, wouldn't "beta" be a better name?

Thanks for your effort.

Bye,

Alan

**Comment by 50Wliu** [comment]
A "draft" state means that the release is not yet final and has not been published.  In other words, it's still being worked on (and can only be seen by project maintainers).  See also #9595.

Hope that answers your question this time - if not feel free to comment here :).

**Comment by alanfranz** [comment]
Yes, now I looked at the other ticket and I got that; I shouldn't look at
the tags, even though I've got the very same issue as #9595 - the atom feed
for atom releases includes tags. I'll work around it.

Thank you!

**Comment by 50Wliu** [comment]
1.2.1/1.3.0-beta2 are now out.
