### ISSUE TITLE
Problem With Horizontal Scroll in Specific Condition

### ISSUE THREAD

**Issue by mssio** [atom/atom#9649]
I have created a file to replicate this problem here:
https://gist.github.com/mssio/2e559b6d53de7a2e2438

Before you copy the content of the files in Atom please make sure that the width of your atom window is not super wide (can't display more than 150 chars) and the height of your atom window is not super tall (can't display more than 60 lines). Also make sure that the atom configuration on soft wrap is turned off.

After you copy the file you can see on line 1, everything is normal, you can use horizontal scroll and continue typing on line 1 and automatically scrolled to follow the cursor. But let's try to see the line 105, in that line we can't do a horizontal scroll and if I type on that line, the window will not follow the cursor.

This is really annoying problem because a lot of my code have a format like this and when I am in the middle / bottom, I will not be able to edit the code using Atom. I have to switch to another text editor.

I hope this is not a duplicate issue, please just close it if it is a duplicate. And I am sorry for my bad English.

**Comment by abe33** [comment]
Hi @mssio, could you tell us the version of Atom you're running? As well as your OS?

**Comment by mssio** [comment]
Hi @abe33, I am using Atom 1.2.0 in os x 10.11.1. I have also tried it on Atom 1.2.0 in Windows 10 too.

**Comment by mssio** [comment]
Hi @abe33, I've just updated my Atom to version 1.2.1 and the problem is still there.

**Comment by abe33** [comment]
In can confirm this issue on beta as well. 

Here's a little gif that demonstrate the problem: 

![horizonta-scroll-issue](https://cloud.githubusercontent.com/assets/247140/11239579/3a0cfe30-8ded-11e5-91cc-18a6e697c060.gif)

As you can see, when reaching the last line of the file, it's no longer possible to scroll horizontally (either with the mouse or by moving the cursor to the end of the line).

@as-cii, @nathansobo: Could it be related to the new way of measuring the text editor's content?
