### ISSUE TITLE
Tab line rendering seems odd

### ISSUE THREAD

**Issue by mcnesium** [atom/atom#9651]
![bildschirmfoto 2015-11-17 um 15 42 02](https://cloud.githubusercontent.com/assets/476060/11214506/f154b670-8d41-11e5-9d1f-fe076c7906cd.png)

The tab lines seem not to be in equal distance of each other. Also, one line is broken apart. Finally, there are no spaces or tabs in the last row, so there should not be any tab lines either.

This is v1.2.0 on OSX 10.11

**Comment by 50Wliu** [comment]
Duplicate of #9369, please subscribe there for updates.
