### ISSUE TITLE
Smart tabs support (tab indent, space alignment) can be improved

### ISSUE THREAD

**Issue by oh-ren** [atom/atom#9652]
Hi there,

To be clear: smart tabs == tabs for indenting, spaces for alignment.

My settings: `softTabs: false, tabLength: 4`

So I like to use aforementioned 'smart tabs', but Atom's support is lacking in this regard.
What I do is, e.g. when aligning variables, press space 4 times (4 because, in this example, `let` or `var` is 3 characters long + a space).
At the same time, although I'm using hard tabs, Atom treats the 4 spaces as one _soft_ tab / 'indent position', meaning e.g. I can jump over it pressing left or right once (I can confirm they **are** spaces actually when inspecting _invisibles_). When having an other amount of alignment spaces, Atom will always interpret soft tabs in alignment with the `tabLength` I'm using (e.g. 9 spaces will result, in this case, to 2 soft tabs + 1 space).

Now, after pressing enter after the first line I aligned with spaces (and is hard-tabbed indented), I'd expect the editor to start/indent + align the next line the same way (e.g. Sublime Text does this well). Atom however transforms every _tabLength_ amount of spaces to a hard tab.

Related to this it would be cool/nifty if a tab pressed inside/before/after alignment spaces would actually insert spaces instead of a hard tab (also because I can't imagine in what situation such would be desirable - so it helps in preventing the unintentional..)

Cheers! :hibiscus:

**Comment by polarathene** [comment]
Are you sure the invisibles are accurate? I've just noticed that hard tab after indents shows a tab invisible followed by however many space invisibles which is normally blank. I assumed it was being smart with space insertion, but upon opening the file in another text editor, they are in fact tabs with no spaces.
