### ISSUE TITLE
Find/replace with multiple root folders does not exclude ignored files

### ISSUE THREAD

**Issue by dominicbarnes** [atom/atom#9656]
When doing a find/replace with a single folder open, the files ignored via `.gitignore` are excluded from the search results. (as expected)

However, when multiple root folders are in use, the previous exclusion doesn't apply and it will search every file for all the root folders. (not respecting the `.gitignore` anymore)

I'm not sure if this is related directly to #5728 or not, as I didn't see this issue mentioned there.

**Comment by abe33** [comment]
Hi @dominicbarnes, it was already reported in atom/find-and-replace#508, please subscribe there to follow the work on this issue.
