### ISSUE TITLE
Custom action for "Cmd-1" key

### ISSUE THREAD

**Issue by ihorskyi** [atom/atom#9657]
Is it possible to override **cmd-1** key? Just wanted to assign "cmd-1" combination as it is by default in intellij idea/webstorm.
Trying to do like this in *keymap.cson*:
```cson
'body':
 'cmd-1': 'tree-view:toggle'
```
but it still behaves the same as before overriding - opens first tab

**Comment by mnquintana** [comment]
Would you mind pasting the full contents of your `keymap.cson` here?
