### ISSUE TITLE
pane:close-other-items with keybinding inserts an unexpected `„` character

### ISSUE THREAD

**Issue by efatsi** [atom/atom#9661]
When using key bindings to trigger pane:close-other-items and there exist unsaved pane items, a `„` character is dropped on the cursors position once you close the save dialog box.

**Reproduction Steps:**
1. Open a saved file
2. Open a new file and throw some text in it
3. Go back to the first file
4. Use keybindings to close other tabs (`cmd-k alt-cmd-w` on darwin [by default](https://github.com/atom/atom/search?utf8=%E2%9C%93&q=close-other-items))

**Expected behavior:**

All other tabs close and I carry on with my day

**Observed behavior:**

All other tabs close and a `„` character appears where my cursor is in the active tab

**Screenshots and GIFs**

![gif](http://i.imgur.com/MjODFOL.gif)

**Atom version:** 1.2.0
**OS and version:** OS X Yosemite 10.10.5

**Installed packages:**

Don't think any I have installed are relevant to the issue.

**Additional information:**
- Problem can be reproduced in safe mode: Yes
- Problem started happening recently, didn't happen in an older version of Atom: No
- Problem can be reliably reproduced, doesn't happen randomly: Yes
- Problem happens with all files and projects, not only some files or projects: Yes
- **Problem does not happen if you use the command palette instead of the key binding.**

**Comment by efatsi** [comment]
@benogle does the `needs-reproduction` label imply that you're unable to reproduce this yourself?

**Comment by alexrussell** [comment]
I know this is seriously old but I saw this issue as I was looking for something else and was intrigued. Anyway, getting to the point I have just followed the steps and it *does not* happen for me.

Atom 1.13.0-beta5, OSX 10.11.6.

Maybe it has since been fixed or was something specific to you, @efatsi?

**Comment by efatsi** [comment]
Thanks for checking in @alexrussell. Looks like this issue has resolved itself somehow in the last year. Always great when that happens.

**Comment by alexrussell** [comment]
Woohoo ✨
