### ISSUE TITLE
Atom Upgrade Fail 1.0.19 -> 1.2.1

### ISSUE THREAD

**Issue by littlebee** [atom/atom#9671]
OSX 10.10.5

When I start atom, in the atom menu, it say's, "Downloading Update" and after a while says, "Restart and Install Update".   When selected, atom closes, does not restart and when restarted manually, says "Downloading Update", rinse & repeat.

I think a factor may be because I noticed first that packages were out of date, started upgrading those and then noticed that atom was out of date and started updating atom before the packages finished updating?

**Comment by jdelisle** [comment]
I'm having similar issues on OSX 10.10.5 as well.

The `Release Notes` page doesn't show updates after 1.1.0. However, the `About` page shows I'm on 1.2.1.

The `Release Notes` page keeps showing the `Restart and update` button. If I click it, it closes Atom but doesn't restart. When I restart manually, it still shows the same as before.

**Comment by zenopopovici** [comment]
I have the same issue as @jdelisle.

**Comment by AlecRust** [comment]
Yup, same issue as @jdelisle.

**Comment by thabemmz** [comment]
+1 same here on OSX 10.11.1. I was stuck on version `2.0` and this caused `Restart and Install Update` to pop up again, while Atom was still on version `2.0` after installing. Eventually a reinstall of Atom resolved the issue for me.

**Comment by frankhale** [comment]
Since @jdelisle mentioned the issue with release notes not updating properly. I'm linking the following issue. 

https://github.com/atom/atom/issues/3757

**Comment by jdelisle** [comment]
@frankhale Oh! This issue seems to have a long history... my issue is a duplicate of yours and https://github.com/atom/release-notes/issues/39.

**Comment by frankhale** [comment]
Thanks!

**Comment by alrico88** [comment]
I've got the same issue. Mac OSX 10.11.2 beta.

**Comment by collinjackson93** [comment]
Same issue on Windows 10. Currently on 1.2.4, but Release Notes shows 1.1.0 is the latest available update. Also, the "Restart and Update" button on Release Notes is always available to be clicked.
