### ISSUE TITLE
Can't switch between windows from the Window menu

### ISSUE THREAD

**Issue by weaverba137** [atom/atom#9675]
In the latest versions of Atom for Mac OS, the list of open windows is missing from the Window Menu.  This makes is annoying to switch between windows.  Please see the attached screenshot which shows two Atom menus, and neither of them listed in the Windows Menu.

![windowmenu](https://cloud.githubusercontent.com/assets/3780690/11241480/231e3f96-8dc9-11e5-89fe-99edf5d7d39b.jpg)

**Comment by 50Wliu** [comment]
Fixed in the 1.3.0 betas.
