### ISSUE TITLE
Atom crash on moving a Firefox tab on it

### ISSUE THREAD

**Issue by AamuLumi** [atom/atom#9676]
Hi,

I found a strange bug : when I move a Firefox tab on Atom, Atom crashes instantly.
Yes, this is a useless bug, but I work with my browser next to Atom, and sometimes I do a bad movement. And Atom crashes.

I'm on Ubuntu 15.04.

**Comment by 50Wliu** [comment]
Please update to Atom 1.2.0 which should have fixed this.
