### ISSUE TITLE
No longer possible for package to have a pane item deserialized along text editors

### ISSUE THREAD

**Issue by abe33** [atom/atom#9677]
Actually it works on 1.2.1 but is broken on beta.

In [tablr](https://github.com/abe33/atom-tablr) I have made my CSV editor class serializable so that quitting Atom with a csv editor open restores it on the next run. For that purpose I have a method on my package main module that loads all the models and views required to make that possible and registers the deserializers as soon as the package is loaded: 

![tablr_coffee_-__users_c_nehemie_github_tablr_-_atom](https://cloud.githubusercontent.com/assets/247140/11245265/19604b86-8e12-11e5-9f94-06a1fe0ec839.png)

However, as you can see below, when reloading Atom with my table editor open, it first tries to deserialize the object, and then loads the package: 

![tablr_coffee_-__users_c_nehemie_github_tablr_-_atom](https://cloud.githubusercontent.com/assets/247140/11245281/2f636f1c-8e12-11e5-8f71-eafd5d519c2d.png)

Is it a regression? Or was it decided to remove this feature?

**Comment by benogle** [comment]
cc @nathansobo is this fixed with your recent deserializer fix?

**Comment by nathansobo** [comment]
Yes, it should be. Please try again on latest 1.2.2 and let us know if there are any issues.
