### ISSUE TITLE
Helper pegs to 100% CPU running Repository::GetCommitCount

### ISSUE THREAD

**Issue by jryans** [atom/atom#9680]
Today when I opened Atom (same result with both Atom Beta 1.3.0-beta3 and Atom 1.2.1), I end up with an Atom Helper process that goes to 100% CPU after a few seconds and remains there indefinitely. I am on OS X 10.10.5.

Here's a screenshot from profiling the process in Activity Monitor:

![atom-profile](https://cloud.githubusercontent.com/assets/279572/11250120/8bf1e1a4-8df0-11e5-89ec-8a63745f8639.png)

I have tried running in safe mode (`atom --safe`), but that does not seem to change anything.

I have used Atom for many months without this issue, and it only appeared suddenly today. What can I do to help diagnose / fix this? Thanks!

**Comment by haraldox** [comment]
+1

same here with Atom beta 1.3.0-beta6 and latest 1.2.4; though not sure if the culprit is the above function call! also took samples directly after launch, but no clue

love my atom, need it back!! unusable as of today

[Sample of Atom Beta Helper.txt](https://github.com/atom/atom/files/48399/Sample.of.Atom.Beta.Helper.txt)
[Sample of Atom Helper.txt](https://github.com/atom/atom/files/48400/Sample.of.Atom.Helper.txt)

<img width="1440" alt="screen shot 2015-12-01 at 12 01 57" src="https://cloud.githubusercontent.com/assets/135914/11499021/72f22aa0-9823-11e5-8bd4-b3fd83fb80cf.png">

may be related to https://github.com/atom/atom/issues/8908

**Comment by thedaniel** [comment]
@jryans is there anything notable about the git repository you're trying to open? Is it huge, or nested, or anything like that?

**Comment by jryans** [comment]
@thedaniel The repo is [gecko-dev](https://github.com/mozilla/gecko-dev/), the source for Firefox, so it does have a fairly high commit count. There are no submodules, nested repos, or other "exotic" repo structures. Just lots of commits.

In my local repo, I get the following rough commit count:

```sh
$ git rev-list HEAD --count
451676
```

**Comment by jryans** [comment]
This issue no longer seems to happen for me. I am unsure if a later build of Atom resolved it or if something else changed. Anyway, I'll reopen / refile if it comes back.

**Comment by jryans** [comment]
This is now happening again for me with Atom 1.4.0-beta3.

**Comment by joshaber** [comment]
@jryans Just to provide more context for this, `GetCommitCount` is used to calculate how ahead/behind the branch is, relative to the upstream branch. Does that shed any more light on why it's so expensive in that repository?

**Comment by jryans** [comment]
Right, I noticed this after digging into the source a bit more. I made a custom build where I just commented out the call to `GetCommitCount`, and the perf problem does go away, so at least I know that's the right area to be checking.

It doesn't seem like `GetCommitCount` should be slow in this repo, as I am only ever a few commits off of upstream, like you'd expect in the usual case.

@joshaber Do you know how I can attach a debugger to `GetCommitCount`? I saw that it's run as a task in a separate helper process, so Atom's built-in DevTools don't seem to be able to debug it.

**Comment by joshaber** [comment]
>It doesn't seem like GetCommitCount should be slow in this repo, as I am only ever a few commits off of upstream, like you'd expect in the usual case.

Yeah, that's interesting. The implementation [calculates the merge base](https://github.com/atom/git-utils/blob/b5bb0a4351aa3108221adeea945fdb9c4b36fadb/src/git.coffee#L102), which I don't think is actually necessary. If you're feeling adventurous, you could try replacing the entire implementation of `Repository::getAheadBehindCount` with a call to [`git_graph_ahead_behind`](https://github.com/libgit2/libgit2/blob/700f0aff24d9b292f24d802c3af3b5c1705193c5/include/git2/graph.h#L37) which should be more efficient.

>@joshaber Do you know how I can attach a debugger to GetCommitCount? I saw that it's run as a task in a separate helper process, so Atom's built-in DevTools don't seem to be able to debug it.

Sadly I don't. @atom/core Anyone know?

**Comment by nathansobo** [comment]
We've setup debugging on child processes... though in theory it should be possible. We are working on web worker support which is baked into the dev tools. For now, maybe you could hack it into the foreground temporarily to investigate it?

**Comment by jryans** [comment]
@joshaber I'm trying to test my changes to the git-utils module, but I can't seem to get a working Atom build. Here's what I did:

1. Clone `git-utils`
2. Make changes to `git-utils`
3. In `git-utils` dir, run `npm link`
4. In `atom` dir, run `npm link git-utils`
5. Rebuild `atom` with `script/build --install-dir /Users/jryans/Applications/AtomDebug.app --verbose`

This causes Atom to fail on startup with:

```
Error: Cannot find module '../build/Release/git.node'
```

What the expected workflow for testing module changes in Atom?

**Comment by jryans** [comment]
To be clear, I do have a working Atom build without my local changes.

**Comment by joshaber** [comment]
Ah yeah, so `git-utils` is a bit funny. After `apm link`ing you'll need to `apm install` in `git-utils` again.

**Comment by jsnajdr** [comment]
@jryans Do you still have this issue? It started happening to me today and it seems the [Repository::getUpstreamBranch](https://github.com/atom/git-utils/blob/master/src/git.coffee#L71-L85) computes the upstream branch wrong when your remote is configured to name the local tracking branch differently from the remote one. E.g., I have this in my config:

```
[remote "origin"]
        url = hg::https://hg.mozilla.org/mozilla-central
        fetch = +refs/heads/branches/default/tip:refs/remotes/origin/master
```

This gives my local tracking branch a nice `origin/master` name instead of `origin/branches/default/tip`. Follow the getUpstreamBranch algorithm and see where it leads you. In my case, it was a stale reference to some old commit, not the current upstream.

**Comment by jryans** [comment]
I believe the issue is still correct, though I'll need to check again... At the moment, I use a custom build of Atom where I just ripped out these problem bits since I don't use them at all. Of course, that means I don't get any updates either... :cry:

Scanning my `git config`, it looks I don't have the same situation as you. I am using the "long" names that match the remote branch. However the Atom code might still be doing something odd here. It's a good thing to look into!

**Comment by jryans** [comment]
I am no longer using Atom, so I'm not sure of the current status. I guess I'll close this.
