### ISSUE TITLE
Draft releases get stuck on the wrong version number

### ISSUE THREAD

**Issue by nathansobo** [atom/atom#9682]
Once a draft release gets created with the wrong version number, which can happen whenever we run a build without bumping the version, all future builds upload to this draft release even if the version number in the `package.json` has changed.

It would be nice to create a new draft release or update the existing one so the version number matched.

/cc @maxbrunsfeld

**Comment by eddiemonge** [comment]
Is this why atom's release notes in the app aren't updating?

**Comment by benogle** [comment]
> Is this why atom's release notes in the app aren't updating?

No, that's an issue with the release notes package.

**Comment by 12hys** [comment]
> No, that's an issue with the release notes package.

@benogle, is this what I'm experiencing here?

![screen shot 2015-12-07 at 10 50 45 am 2](https://cloud.githubusercontent.com/assets/4165861/11631571/a0b1d93e-9cd0-11e5-9591-e8e7b0f25e3b.png)

The release notes are saying I'm at version 1.1.0, and the "Restart and update" button doesn't do anything.

**Comment by benogle** [comment]
Yes

**Comment by pixelchutes** [comment]
Confirmed. Sounds like a manual fix for end users is not an option then?

![release_notes](https://cloud.githubusercontent.com/assets/352182/11757943/c836f930-a022-11e5-962e-0e77c757aa4d.jpg)

**Comment by 50Wliu** [comment]
> Confirmed. Sounds like a manual fix for end users is not an option then?

The issue you're describing and the issue that @nathansobo is describing are *not* the same.  For your issue, please subscribe to atom/release-notes#39 for updates.  That issue also contains some possible workarounds.

**Comment by pixelchutes** [comment]
Perfect, thanks @50Wliu.
