### ISSUE TITLE
DevTool Window's Location Not Restore On Non Primary Monitors

### ISSUE THREAD

**Issue by francoislaberge** [atom/atom#9685]
I've been developing a slick workflow for our development environment for remembering all window state of open windows so that they are restored at running our system each time. I can't figure out how to get access to and restore the window properties of any windows devtools. I can serialize it's shown/hidden state, but that's it. 

Electron seems to remember it's location, but not which display it was over. For example, if I put the devtools window 100 pixels downward from the top of my second monitor, it will get restored to 100px down from the top of my primary monitor.

Is this the expected behavior? Any times on getting access to reading/setting the bounds of devtools windows? 

Related: I've been working on [http://npmjs.org/debugger](http://npmjs.org/debugger) which wraps node-inspector as an electron app and makes debugging node.js scripts easier. I could really use this functionality for that app too.

Any help is appreciated,
Francois

**Comment by chandrachivukula** [comment]
was looking into a similar issue trying to find if there is an API to detect which monitor the app is running on (so we can restore the app in its previously running location)
