### ISSUE TITLE
Mac os (El Capitan) crash all instances after closing window

### ISSUE THREAD

**Issue by Yontih** [atom/atom#9692]
Attached dump.

[atom_dump.txt](https://github.com/atom/atom/files/38712/atom_dump.txt)

**Comment by joaosamouco** [comment]
Same happens to me when I have three instances of Atom in full-screen mode and close one of them.

**Comment by izuzak** [comment]
Thanks for the report, @Yontih 

cc @zcbenz -- there's a crash report attached.

**Comment by 50Wliu** [comment]
Refs #9584.

**Comment by LexGear** [comment]
Yes, same issue for me after Unity opens an atom window and I close it. Whole program crashes. El Capitan.

**Comment by LaurentGoderre** [comment]
I have this behavior too but only when I close the config folder

**Comment by OmgImAlexis** [comment]
Same for me, I closed a window and it instantly crashes. [Here's the crash report](https://gist.github.com/OmgImAlexis/f0dd94fa9ae539f191ca).

**Comment by chachan** [comment]
Same here, seems to be happening only when one the the windows is in full-screen mode

**Comment by faceair** [comment]
Same for me.

[atom_dump.txt](https://github.com/atom/atom/files/41767/atom_dump.txt)

**Comment by zcbenz** [comment]
From the crash report, this is a duplicate of #9584.

**Comment by Ecleptic** [comment]
Mine still crashes. Full screen just one tab open or with 3, it doesn't matter. I Hit Cmd-Q and get a crash.
[Crashdump.txt](https://github.com/atom/atom/files/65805/Crashdump.txt)

**Comment by 50Wliu** [comment]
@Ecleptic please update to the 1.4.0 betas.
