### ISSUE TITLE
Open DevTools with alt-cmd-i on OSX

### ISSUE THREAD

**Issue by jccguimaraes** [atom/atom#9697]
When opening the devTools with alt-cmd-i on OSX it added an **`1`** to opened file cursor position

**Comment by jccguimaraes** [comment]
Since upgrading from 1.2.0.
Have disabled all communities packages and reloaded.

**Comment by izuzak** [comment]
Thanks for the report, @jccguimaraes. I'm having trouble reproducing this. Can you provide a GIF which clearly demonstrates the problem, and make sure that you're recording the GIF with Atom running in safe mode and that the keybinding resolver is visible?

https://github.com/atom/atom/blob/master/CONTRIBUTING.md#how-do-i-submit-a-good-bug-report

**Comment by jccguimaraes** [comment]
Sorry about that.
Opened in safe mode and toggled keybind resolver.
![9697](https://cloud.githubusercontent.com/assets/14871650/11273079/3bea20fc-8ec9-11e5-9ecb-5dd8d0672914.gif)

**Comment by izuzak** [comment]
That's not safe mode. You start safe mode with `atom --safe`, not `atom -safe`.

**Comment by jccguimaraes** [comment]
damn...missed an - :\
![9697](https://cloud.githubusercontent.com/assets/14871650/11273219/e4cfd1f8-8ec9-11e5-9dbd-198e62e3ae2f.gif)

**Comment by nathansobo** [comment]
I can reproduce a slightly different behavior, where `cmd-alt-i` inserts a `^`. Interestingly, `alt-i` alone inserts a `^` as the start of a multi-stroke accented character sequence. For some reason, we don't seem to be stopping this accented character from being inserted when we recognize the binding. This is probably due to a change in Chromium.

**Comment by nathansobo** [comment]
@jccguimaraes What keyboard layout are you using. I just noticed that when I switch back to a U.S. Keyboard from Dvorak that this stops happening. Weird.

**Comment by jccguimaraes** [comment]
@nathansobo I am using QWERTY on OSX El Capitan.
A college of mine also has the same behaviour as i do (same type of mac).
Hope it helps.
