### ISSUE TITLE
1.2.3 deb missing

### ISSUE THREAD

**Issue by forivall** [atom/atom#9702]
The .deb file is missing from the build page.

**Comment by matanster** [comment]
I think you can get to it from the button at https://atom.io/.

**Comment by 50Wliu** [comment]
Hmm, it does appear to be missing.  Probably a build timeout/error of some sort.
/cc @nathansobo

**Comment by maxbrunsfeld** [comment]
Thanks for the report! Fixed.

**Comment by matanster** [comment]
Does this deb file run over user settings if installed on top an older version? I gather no other upgrade mechanism for linux to date.

Sent from my mobile

-------- Original Message --------

**Comment by maxbrunsfeld** [comment]
@matanster Your user settings should not be affected by installing another version of Atom. But no, we don't have an auto-update mechanism in place for linux.

**Comment by forivall** [comment]
No, just like package updates from a repository, manual package updates on linux do not run over user settings. (I maintain [aur/atom-editor-beta-bin](https://aur.archlinux.org/packages/atom-editor-beta-bin) and co-maintain [aur/atom-editor-bin](https://aur.archlinux.org/packages/atom-editor-bin/) (for Arch Linux and variants, such as Manjaro and Antergos).)

**Comment by matanster** [comment]
Great! :+1:
