### ISSUE TITLE
Add version number in download section

### ISSUE THREAD

**Issue by greencopper** [atom/atom#9703]
On the website https://atom.io/ there is a download button for .deb and .rpm, it would be really great if the package names would contain the version number to.

**Comment by mnquintana** [comment]
Thanks for the suggestion! This looks like a duplicate of https://github.com/atom/atom.io/issues/12 - feel free to subscribe there for updates.

You might also want to take a look at the [Contributing guide](https://github.com/atom/atom/blob/master/CONTRIBUTING.md#atom-and-packages) for a guide on where to post issues.
