### ISSUE TITLE
Mac Git Diff Window Focus Issue

### ISSUE THREAD

**Issue by LexGear** [atom/atom#9704]
I've tried recreating this issue on windows but can't seem to replicate, and about 5% of the time on Mac I don't have the issue but most the time I do.

Particularly with Unity3D game projects, even when Unity is not running, a changed file will be marked as orange in atom, to then click outside atom and then back into atom all files are remarked as not changed (white).

**Comment by squio** [comment]
Strangely I see the very same effect after updating git for OSX to v 1.9.2

Test:

1. Edit a file which is under git
2. Atom shows filename in orange in the file view (or green when file was new created)
3. Focus any other app (e.g. CMD-TAB to Finder) and back to Atom
4. File view reverts to "not changed" - white in dark theme / black in light theme

New file added and saved, Atom front most app:
<img width="168" alt="screen shot 2016-08-04 at 19 59 21" src="https://cloud.githubusercontent.com/assets/169410/17412653/28192574-5a7e-11e6-9a4a-2beffd87e4da.png"> 

After switching to Firefox (or Finder, or any app) and back to Atom:
<img width="165" alt="screen shot 2016-08-04 at 19 59 31" src="https://cloud.githubusercontent.com/assets/169410/17412667/38277c68-5a7e-11e6-9c61-e1f29c9e0e45.png">

The switch to "neutral" doesn't happen instantaneous but after a fraction of a second so it looks that Atom decides about the `git` status only just after Atom becomes frontmost app again.

Is there some way to get a verbose log of what is going on under the hood?

**Comment by mnquintana** [comment]
Closing in favor of https://github.com/atom/tree-view/issues/906
