### ISSUE TITLE
Can't revert back to Featured Packages list in Install Packages

### ISSUE THREAD

**Issue by jonobacon** [atom/atom#9705]
Hi Folks,

I just wanted to report a small issue (possibly not an issue, depending on your view).

I am currently running 1.2.1 and in the *Install Packages* screen I see the Features Packages. This is really helpful for new Atom users.

I can then search for a specific package (e.g. `emmett`), but then when I remove the search term from the text box it doesn't go back to the Featured Packages view. As such, the only way to see the Featured Packages is to restart Atom (switching from a different settings view back to Install Packages doesn't reset the view).

# Potential Solutions

A few options for resolving this:

**Reset View Based on Typing**

When the user deletes the search box so there are no characters, it could then re-instate the view.

**Provide a Link**

Another option is that a link to *Featured Packages* (and potentially other searches such as *Popular Packages) under the search box.

**Comment by amytruong** [comment]
@jonobacon definitely seems like a user experience issue to me! :grimacing: 
Do you mind moving this issue over to [/atom/settings-view](https://github.com/atom/settings-view) so we can get it in the correct repo? 
Thank you! :pray:

**Comment by jonobacon** [comment]
No problem, @amytruong. It is now living at https://github.com/atom/settings-view/issues/705

**Comment by amytruong** [comment]
:sparkles: thank you so much @jonobacon! :smile:
