### ISSUE TITLE
Window dropdown should show all of the Atom windows

### ISSUE THREAD

**Issue by elifoster** [atom/atom#9708]
It's pretty standard (on OSX) for the Window dropdown to display all windows the application has open. This makes it a lot easier to reshow minimized windows. Currently, the only way to do it is to right click the dock icon and select 'Show all Windows', then find your desired window. Adding this dropdown would greatly improve productivity on OSX.

**Comment by 50Wliu** [comment]
This has been fixed in the 1.3 betas.
