### ISSUE TITLE
local atom Release Notes is outdated

### ISSUE THREAD

**Issue by Heather** [atom/atom#9713]
Windows 10

Atom 1.2.3

In local Release Notes recent version is 1.1.0

**Comment by thorade** [comment]
Same problem here, see screenshot below.
I can click the "Restart and update" button as often as I want, nothing changes.

![atom_releasenotesoutdated](https://cloud.githubusercontent.com/assets/314571/11295329/0c95fc3e-8f6b-11e5-8bb9-aeedbf4d75d6.png)

**Comment by davidspiess** [comment]
Same here with 1.2.3 on Windows 8

**Comment by fmaida** [comment]
I  can also confirm this problem on Mac OS X 10.11.1

**Comment by ashrayjain** [comment]
Same issue on Mac OS X 10.10.5 with Atom 1.2.3

**Comment by Alhadis** [comment]
Oh geez, I'm glad I'm not the only one having this issue. I actually just reinstalled Atom thinking it was only a problem on my end...

Whew, guess I'm not crazy, then.

**Comment by mnquintana** [comment]
Thanks for the report! This is a duplicate of https://github.com/atom/release-notes/issues/39 - feel free to subscribe there for updates.
