### ISSUE TITLE
Escape button does not work

### ISSUE THREAD

**Issue by deeperx** [atom/atom#9716]
Escape does not close modal windows like ```Cmd+P```, ```Cmd+F``` etc. What could be the problem?

**Comment by izuzak** [comment]
@deeperx Can you please provide more helpful information with your reports?

https://github.com/atom/atom/blob/master/CONTRIBUTING.md#reporting-bugs

I'm happy to reopen this when you do; the escape key works fine for me. Thanks!

**Comment by gaoshijun1993** [comment]
I have the same problem,here is my escape button keybindings :
escape	tool-panel:unfocus	Core	.tool-panel.panel-left, .tool-panel.panel-right
escape	editor:consolidate-selections	Core	atom-text-editor , atom-text-editor[mini]
escape	core:cancel	Core	body
escape	core:cancel	Go To Line	.go-to-line atom-text-editor[mini]
escape	core:cancel	Tree View	.tree-view-dialog atom-text-editor[mini]
escape	autocomplete-plus:cancel	Autocomplete Plus	atom-text-editor.autocomplete-active
