### ISSUE TITLE
Deep linking to a package's settings page

### ISSUE THREAD

**Issue by francoislaberge** [atom/atom#9722]
is there a way to open a package's settings page? It'd be nice to be able to have a button or other interface element to send users to a package's settings page.

**Comment by mrodalgaard** [comment]
`atom.workspace.open 'atom://config/packages/<package-name>'` will open your package settings page in a new tab.

**Comment by francoislaberge** [comment]
Thanks. That works except when the preferences are already open and then it won't do anything but stay on whatever page it was already on. Trying to figure out a way around that.

**Comment by 50Wliu** [comment]
The `atom://` handler isn't very robust yet unfortunately.

**Comment by benogle** [comment]
> That works except when the preferences are already open and then it won't do anything but stay on whatever page it was already on

That is an issue with the settings-view. Can you open an issue on the [settings-view](https://github.com/atom/settings-view/issues) package on that topic?

**Comment by francoislaberge** [comment]
Done
