### ISSUE TITLE
Slow performance with maximized window Ubuntu

### ISSUE THREAD

**Issue by leifcr** [atom/atom#9724]
I'm seeing degraded performance while a window is maximized on Ubuntu. Works perfect if the window is either fullscreen or non-maximized.

Cpu profile, heap screenshot can be found here:
https://github.com/leifcr/atom_maximized_performance_ubuntu_issue

Steps to reproduce:
* Open Atom 1.2.1 or Atom 1.3.0-beta4 in safe mode
* Open testfile1.txt and testfile2.txt
* Tab between the files in maximized window state.

System configuration:
Ubuntu 15.10
Resolution 3200x1200
Intel HD Graphics 5000
Intel Core i7-4702hq
16 GB ram
SSD drive

Same configuration, but running in lower resolution 1920x1080 works like it should.

Gif for maximized window:
![Maximized window tabswitching]
(https://raw.githubusercontent.com/leifcr/atom_maximized_performance_ubuntu_issue/master/maximized_tab_switching.gif)

Gif for fullscreen:
![Full screen tab switching]
(https://raw.githubusercontent.com/leifcr/atom_maximized_performance_ubuntu_issue/master/fullscreen_tab_switching.gif)

Shows the difference and the slow drawing of the window in maximized state.

**Comment by leifcr** [comment]
@benogle I suspect it might only be the combination of ubuntu 15.10, Intel Graphics 5000 and 3200x1200 resolution, as I've tried various setups with Ubuntu 15.10 + Nvidia or AMD graphics and 3200x1200 resolution, and they don't seem to suffer from the same issue.

**Comment by alexandrudima** [comment]
@leifcr Did you ever find a workaround for this. VSCode also uses Electron/Chromium and @eugen-v hit a similar issue under similar circumstances in VSCode.

**Comment by leifcr** [comment]
@alexandrudima i didn't find a solution, so I'll have a look at vscode and see if I can reproduce similar  results.

**Comment by leifcr** [comment]
After getting info on Microsoft/vscode#162 that it might be related to mesa/chromium issues, I've updated to the drivers in this ppa: https://launchpad.net/~oibaf/+archive/ubuntu/graphics-drivers, and perfomance is equal in maximized, full screen and scaled windows. I'll raise an issue against the graphics drivers on Ubuntu.

**Comment by leifcr** [comment]
Filed against ubuntu here: Filed against ubuntu here: https://bugs.launchpad.net/ubuntu/+source/xserver-xorg-video-intel/+bug/1525207

**Comment by leifcr** [comment]
@50Wliu Since it's a ubuntu driver issue, I'm closing this here.

**Comment by patoi** [comment]
Related to #9561 (?)
