### ISSUE TITLE
Open windows don't show in the window menu

### ISSUE THREAD

**Issue by lucasmarshall** [atom/atom#9728]
OS: Mac OS X
OS version: 10.11.1
Atom version: 1.2.3

The window menu in the menu bar doesn't show any open Atom windows. Tested in safe mode as well.

![screen shot 2015-11-20 at 2 46 15 pm](https://cloud.githubusercontent.com/assets/885074/11313923/bfc2c3c6-8f95-11e5-9464-a368fdc1054e.png)

**Comment by 50Wliu** [comment]
This has already been fixed in the 1.3 betas.
