### ISSUE TITLE
Cannot Open Git Directory inside Dropbox on Surface Pro 4

### ISSUE THREAD

**Issue by JackMc** [atom/atom#9731]
Hello everyone!

I apologize if this bug report is sparse for details... I'd be super happy to provide them if necessary.

I recently bought the low-end Surface Pro 4 for notes and school-related development. I love Atom and I installed it, but unfortunately when I try to open a file or folder, I get an error which seems to say that the whole window has crashed!

As I said, I would be happy to provide any details about my situation that would be needed to resolve the situation. Especially how to get logs to help you guys.

**Comment by 50Wliu** [comment]
What version is this?  I suspect you may be hitting a bug that has been resolved in Atom 1.2.0 and above.

**Comment by JackMc** [comment]
The version of Atom I have is 1.2.3, from the website. Thanks for looking into this!

**Comment by JackMc** [comment]
Just an update: This morning it seems to have started working for file open, but not folder open.

**Comment by 50Wliu** [comment]
Have you installed any packages?  If so, does it still crash after you start Atom in safe mode (`atom --safe`)?  In addition, does it crash on all folders, or just some?

**Comment by JackMc** [comment]
It crashes in safe mode (the only plugin I have installed is markdown-preview-plus for viewing LaTeX in Atom).

After looking into it more it seems it only crashes on my Coursework folder. This folder is a Git repository inside my Dropbox (dunno if Dropbox impacts Atom at all), but it doesn't seem to fail on any of my other Git repositories (that aren't in Dropbox).

**Comment by JackMc** [comment]
(This directory is openable on my Mac)

**Comment by JackMc** [comment]
(Changed title to better reflect issue)

**Comment by 50Wliu** [comment]
Hmm.  If you move the Coursework folder outside of Dropbox, does it load then?  If it still crashes, can you share the folder, or is it private?  I'd like to see if I can repro the crash.

**Comment by JackMc** [comment]
Yeah, it still fails if I move it out. Unfortunately I wouldn't be comfortable sharing it.

If I remove the ``.git`` folder, then the directory works. It may be that this directory is pretty big (it contains all my coursework from this year) (~3000 items including the Git stuff)

**Comment by lee-dohm** [comment]
I suspect this is related to #6674 and the issues that have been happening with libgit2?

**Comment by JackMc** [comment]
Is there any way I can grab a trace back or something?

**Comment by raelyard** [comment]
Crash dumps on Windows can be found in:
C:\Users\<Username>\AppData\Local\Temp\Atom Crashes

**Comment by dddejan** [comment]
I have the same issue on a Surface Book, with Atom 1.4. It's really annoying because every morning I have to:

1. mv .git temp
2. open atom
3. mv temp .git

The crash was happening a month ago when I first installed atom, then it stopped for a while. Then this morning it started again (it worked yesterday).

**Comment by dddejan** [comment]
I checked the dumps and the previous version that was crashing was 1.3.1. It seems like it the problem was reintroduced in 1.4.0.

**Comment by dddejan** [comment]
This is becoming ridiculous. I'm at version 1.8 and it's still crashing. If any developer cares about this I would be more than happy to investigate more if I get some guidance on what to look at.

**Comment by 50Wliu** [comment]
@dddejan If Atom is still generating crash dumps, please upload the latest one here that has to do with the Dropbox crash.
