### ISSUE TITLE
Particle Dev crashed on updating firmware for offline mode

### ISSUE THREAD

**Issue by Kabron287** [atom/atom#9734]
Windows 10 x64
Atom 1.0.19

Any Ideas?

![1](https://cloud.githubusercontent.com/assets/2493191/11318549/6c300060-9068-11e5-8f93-ae71f2eadec2.jpg)
![2](https://cloud.githubusercontent.com/assets/2493191/11318551/6f2799b8-9068-11e5-9349-c718b6339e5f.jpg)

**Comment by 50Wliu** [comment]
Please re-open this on the Particle Dev package.

**Comment by Kabron287** [comment]
Sorry, but I understand nothing.
