### ISSUE TITLE
Update node.dll

### ISSUE THREAD

**Issue by glen-84** [atom/atom#9735]
Node.js 4.1.1.0 is insecure. See https://secunia.com/advisories/66744

Thanks.

Edit: My apologies if this should have been reported @ atom/apm.
Edit 2: This may not directly affect Atom, but it wouldn't hurt to update it anyway.

**Comment by paulcbetts** [comment]
Atom doesn't host HTTP servers, so this bug doesn't apply.

**Comment by glen-84** [comment]
Yep, that's what I was referring to in my second edit. =)
