### ISSUE TITLE
Editor crashed, cannot read property 'substr' of null

### ISSUE THREAD

**Issue by lesaff** [atom/atom#9736]
Atom 1.2.3
OS X El Capitan 10.11.1

![screen shot 2015-11-21 at 7 41 04 am](https://cloud.githubusercontent.com/assets/1151181/11319190/4ffe897e-9023-11e5-9602-6d59eefbab79.png)
![screen shot 2015-11-21 at 7 38 47 am](https://cloud.githubusercontent.com/assets/1151181/11319191/52f93458-9023-11e5-8260-82d881ddc266.png)

**Comment by 50Wliu** [comment]
Can you reproduce this in safe mode (`atom --safe`)?

**Comment by lesaff** [comment]
`atom --safe` opens atom just fine, albeit slower. 
Interestingly enough, I was able to open `atom` normally after that.

Let me see if I can reproduce this error after reboot.

Thx

**Comment by izuzak** [comment]
@lesaff Can you provide the crash report for that crash? You can find some instructions on how to find it [here](https://github.com/atom/atom/blob/master/CONTRIBUTING.md#how-do-i-submit-a-good-bug-report) (under "If you're reporting that Atom crashed"). Thanks!
