### ISSUE TITLE
Option to close success alerts

### ISSUE THREAD

**Issue by jamen** [atom/atom#9741]
![](http://i.imgur.com/QXIGMOZ.png?10)

Success alerts are always great to see, but sometimes you get the memo long before it decides to close.  

These alerts get in the way of panes, tabs, and code, so it'd be nice if there we're a option to close the menu alongside its auto-closing timer, this way we don't have to wait for it to close before we can click something its covering.

**Comment by lee-dohm** [comment]
All notifications, including success notifications, have an option to be dismissable. It is up to the developer displaying the notification to make it dismissable or not. 

Additionally, you have a few options:

1. You can file a bug against the package displaying the notification (it appears to be the [git-plus package](https://atom.io/packages/git-plus) in your example above) stating that you'd like the package's notifications to be dismissable
1. You can file a PR with the package displaying the notification to make the package's notifications dismissable
1. You can disable the notifications package

Also, there are a number of [suggested enhancements to the notifications package](https://github.com/atom/notifications/labels/enhancement) that you might want to subscribe to. If you have other suggestions for enhancements to the notifications package, please file an Issue there.

Thanks for your feedback!

**Comment by jamen** [comment]
Related: https://github.com/akonwi/git-plus/pull/333
