### ISSUE TITLE
Uncaught Error: ENOENT, open 'local_path_to_file\foo.html' when removing a file using Git bash

### ISSUE THREAD

**Issue by figurebelow** [atom/atom#9743]
Uncaught Error: ENOENT, open 'local_path_to_file\foo.html'

**Atom Version**: 0.160.0
**System**: Microsoft Windows 7 Professional 
**Thrown From**: Atom Core

### Steps To Reproduce

1. Edit a HTML file (foo.html)
2. In a bash console rum git rm foo.html
3. Try to modify the file content inside Atom

### Stack Trace

```
At c:\Users\Ruben\AppData\Local\atom\app-0.160.0\resources\app\node_modules\q\q.js:126

Error: ENOENT, open ''local_path_to_file\foo.html'
  at Error (native)

```

**Comment by 50Wliu** [comment]
Please update Atom - you're more than 60 versions behind at this point.
