### ISSUE TITLE
can not uninstall/delete "Atom-Beautify" package on Windows 7

### ISSUE THREAD

**Issue by pSkpt** [atom/atom#9751]
![screenshot_1](https://cloud.githubusercontent.com/assets/2131188/11326817/458071a6-917c-11e5-8a58-f02a31ea01bd.png)

I tried uninstall "Atom-Beatufiy" (*because it's give error on startup and sometimes editor crashed.*)
And that give error trying to uninstall...

So after i try to delete files manually and 'Windows' give error because folder path so long.

![screenshot_2](https://cloud.githubusercontent.com/assets/2131188/11326815/4558ac7a-917c-11e5-9032-a9ebe4fc0f9f.png)

![screenshot_1 2](https://cloud.githubusercontent.com/assets/2131188/11326816/456c7962-917c-11e5-82df-62a20fddf42b.png)

**Comment by pSkpt** [comment]
I solved the problem.
install node.js, and `npm install -g rimraf`
delete folders : `rimraf <dir>`

**Comment by 50Wliu** [comment]
Nice to hear @pSkpt!  Atom will be updating to `npm@3` in the future which will get rid of all of these huge folder paths.
