### ISSUE TITLE
Package doesn't show keyboard shortcut

### ISSUE THREAD

**Issue by screendriver** [atom/atom#9758]
I am using the [atom-preview](https://github.com/Glavin001/atom-preview) package / plugin. It has a keyboard shortcut to show and hide the preview pane. Unfortunately it doesn't show me the shortcut when I am searching for it with control + shift + p like other packages I am using. I've created an issue for that https://github.com/Glavin001/atom-preview/issues/117 and the author of the package told me to ask the question here.

Could you tell me why Atom doesn't display the command Ctrl+Alt+Y?

![screenshot](https://cloud.githubusercontent.com/assets/149248/11334652/b97f032e-91d6-11e5-9287-264e0695b579.png)

**Comment by maxbrunsfeld** [comment]
I can reproduce this on Atom master. When I open the command palette. It doesn't show the key bindings for `Tabs: Close Tab` for example.
