### ISSUE TITLE
lock the cursor and navigate up and down

### ISSUE THREAD

**Issue by caglarcem** [atom/atom#9760]
Not sure if this is fair as an issue, but i tried hard to find a navigation method i used in Visual Studio/ Webstorm.

When I had pressed Ctrl + Up (or Down) arrow , it used to lock the cursor where it is, and slide the editor lines up and down in the background.  

Is this possible in Atom?

**Comment by maxbrunsfeld** [comment]
We don't currently have a key-binding for that, and I don't think we will add that to Atom core. You could easily write a package that does that though. You might use the [scrollToScreenPosition](https://atom.io/docs/api/v1.2.4/TextEditor#instance-scrollToScreenPosition) method, or the experimental [setFirstVisibleScreenRow](https://github.com/atom/atom/blob/master/src/text-editor.coffee#L3184) method.

**Comment by caglarcem** [comment]
Thanks  I'll give it a try
