### ISSUE TITLE
"Tabs: Close Tab" doesn't close window when "Close Empty Windows" is enabled.

### ISSUE THREAD

**Issue by DouweM** [atom/atom#9761]
#9607 introduced the "Close Empty Windows" option, which is described as "When a window with no tabs or panes is given the 'Close Tab' command, close that window." in Settings.

![screenshot](https://cloud.githubusercontent.com/assets/159434/11303872/94600abc-8fa5-11e5-9412-62734caa656a.png)

@izuzak points out (https://github.com/atom/atom/issues/863#issuecomment-158914212) that this works for "File" -> "Close Tab", the Command-W/Control-W shortcuts and the "Core: Close" command in the command palette, but _not_ for the "Tabs: Close Tab" command.

The reason is that "Tabs: Close Tab" is not defined as `core:close`, but as the `tabs:close-tab` command defined by the `tabs` package which is unaffected by this recent change to `core:close` behavior.

We could:
- Change the description of the new setting to make this distinction.
- Change the behavior of `tabs:close-tab` to match that of `core:close`.

I lean towards the latter.

cc @nathansobo @benogle

**Comment by benogle** [comment]
We talked about this today and decided we want to keep the `tabs:close-tab` command atomic and true to its name and only close the tab.
