### ISSUE TITLE
Command + N does not open new window on Mac

### ISSUE THREAD

**Issue by alexdmiller** [atom/atom#9765]
#### Steps
1. Close all currently open Atom windows
2. Press command+n

#### Expected
A new window with a new file should open.

#### Observed
Nothing happens. You must first press command+shift+n to open a window before opening a new file. This is convoluted—everyone understands that command+n means "open a new window".

**Comment by benogle** [comment]
> This is convoluted—everyone understands that command+n means "open a new window"

`cmd-n

**Comment by alexdmiller** [comment]
Nothing. No window or file opens.

**Comment by izuzak** [comment]
I think this is a duplicate of https://github.com/atom/atom/issues/7171, so I'm closing this in favor of that issue. @alexdmiller let me know if I misunderstood your report, and thanks for opening an issue.

**Comment by alexdmiller** [comment]
Yes, that's the same. Thanks.
