### ISSUE TITLE
`stylesheet` persists in the treeview

### ISSUE THREAD

**Issue by jaam0** [atom/atom#9767]
Immediately after a fresh reinstall of Atom (before installing any packages), after `Edit > Open Your Stylesheet`, a folder or file `stylesheet` is created in the treeview. Copy-paste its full path (from context menu) shows `atom://.atom/stylesheet`. Every time I restart Atom, no matter what files I had open in the previous session, `stylesheet` is in the treeview. I'm using Atom 1.2.3 on Ubuntu 14.04.2 LTS

**Comment by maxbrunsfeld** [comment]
Some background info on this:

The `Open Your Stylesheet` command opens an Atom URL: `atom://.atom/stylesheet`. This isn't a directory on disk. We currently have some logic for adding non-existent directories as project paths, in order to support Facebook's remote directory packages. See https://github.com/atom/atom/pull/5795.

**Comment by jaam0** [comment]
Yes, definitely a bug. Trying to delete it with context menu gives `The root directory 'stylesheet' can't be removed.` Whenever I close Atom (with or without a file open in a window) and restart it, the treeview shows only `stylesheet`, which persists even after closing `styles.less` (if it's open). When another file is open and I do `Reveal in Tree View` w/ context menu on it, the file isn't revealed and `stylesheet` persists. In other words, once `stylesheet` is in the treeview, it's impossible to get rid of the damn thing other than by (re)moving the `~/.atom/storage` directory. But if I happen to do `Edit > Open Your Stylesheet` again, eth starts all over. Cf. a [thread](https://discuss.atom.io/t/cannot-open-your-stylesheet-in-linux/21840)

**Comment by maxbrunsfeld** [comment]
> Trying to delete it with context menu gives The root directory 'stylesheet' can't be removed.

You should be able to right click it and say `Remove root folder`. To get rid of it, you should just have to open atom with a different path: `atom my-path`.

**Comment by jaam0** [comment]
Thanks, this works
