### ISSUE TITLE
TextBuffer::getTextInRange() incorrect?

### ISSUE THREAD

**Issue by Arcanemagus** [atom/atom#9768]
This may simply be a misunderstanding, but it seems that `TextBuffer::getTextInRange()` is returning incorrect values.

Let's say you have a file consisting entirely of this:
```
foo
```

Since Ranges are 0 based you would expect the following to return "foo":
```JavaScript
buffer = atom.workspace.getActiveTextEditor().getBuffer()
buffer.getTextInRange([[0,0],[0,2]])
```

However it only returns "fo". You need to run the following to get "foo":
```JavaScript
buffer.getTextInRange([[0,0],[0,3]])
```
![image](https://cloud.githubusercontent.com/assets/427137/11347810/e960f48e-91d7-11e5-811f-d55ddcc6e5aa.png)

Are ranges not 0 based, or is something not correct here?

**Comment by maxbrunsfeld** [comment]
No, ranges are zero-based. This is the correct behavior. Think of the range as being analogous to the integer range that you'd pass to [`String.prototype.substring`](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/String/substring).

```js
var string = "foo";
string.substring(0, 0) // => ""
string.substring(0, 1) // => "f"
string.substring(0, 2) // => "fo"
string.substring(0, 3) // => "foo"
```

**Comment by steelbrain** [comment]
@maxbrunsfeld I think we might have confused the methods here.
String class in javascript has multiple methods for string manipulation

 - `String.prototype.substr`
 - `String.prototype.substring`
 - `String.prototype.slice`

I am not sure what method Atom is trying to make ranges compatible with. but If I understand correctly, the ranges and text should be 0-indexed just like you said, which means `"abc"` would mean `['a', 'b', 'c']`, so if we do `['a', 'b', 'c'].slice(0, 3)` we get the same array back. That is the ranges should be like, because if they are not like this then there's a huge confusion in the API.

In our use case we're generating ranges using the line length and then reducing one from it so the range covers all of the text, If we "patch" it to make it work, we will have to remove the reducing one logic, which then defeats all this `0-based` concept.

Please do explain :)

**Comment by steelbrain** [comment]
IIRC, `String.prototype.substring` gets a 0-indexed start point, and then the number of chars to count from that point on. It's not a range at all, it's a diff between start and end.

**Comment by maxbrunsfeld** [comment]
@steelbrain No, it takes a start and an end index (i.e. a range). See the examples above. Maybe you're thinking of `String.prototype.substr`?

**Comment by steelbrain** [comment]
@maxbrunsfeld so we have two options here

 1. Change all the 0-indexed ranges we have to 1-indexed so they cover all the characters
 2. Atom makes it's internal string manipulation methods compatible with `String.prototype.slice` instead of `String.prototype.substring`

Which option would you recommend?

**Comment by Arcanemagus** [comment]
@maxbrunsfeld So should we treat ranges as "areas between the initial number's column and the last number's column, not inclusive"?

We have been treating these "zero-indexed" numbers like you would treat arrays, like the following:
![image](https://cloud.githubusercontent.com/assets/427137/11351279/9ce34f5e-91ea-11e5-9ac6-4f1934838e92.png)

**Comment by maxbrunsfeld** [comment]
@steelbrain @Arcanemagus Ranges, are zero-indexed. `getTextInRange` treats the range's end point as exclusive, just like *all* other javascript APIs: `Array.prototype.slice`, `String.prototype.slice`, and `String.prototype.substring`.

@steelbrain I think you are misunderstanding the situation. Nothing is 1-indexed, and `slice` and `substring` treat work the same (they just handle edge cases like `end` < `start` differently). Atom's methods work the same as both. Atom definitely does not need to change in this regard.

**Comment by steelbrain** [comment]
@maxbrunsfeld I now see that both `slice` and `substr` work the same way for our use case.

so I have another question, imagine I have a line with
```php
$var = "I am something being assigned to a var";
```
so how do we construct a range that covers all of this text? Even the last character.
Here's about what we're doing right now
```js
const textEditor = atom.workspace.getActiveTextEditor()
const charsInLine = textEditor.getBuffer().lineLengthForRow(0)
const range = [
  [0, 0],
  [0, charsInLine - 1]
]
```

**Comment by Arcanemagus** [comment]
The end point being exclusive makes this make sense to me at least, thanks.

**Comment by maxbrunsfeld** [comment]
@steelbrain Your solution is fine. In most cases, you can also do: `[[0, 0], [0, Infinity]]`

**Comment by steelbrain** [comment]
@maxbrunsfeld Unfortunately, that solution does not cover all the text, it leaves the last char out of range. You can confirm it yourself :)
```
const textEditor = atom.workspace.getActiveTextEditor()
const charsInLine = textEditor.getBuffer().lineLengthForRow(0)
console.log(textEditor.getTextInRange([
  [0, 0],
  [0, charsInLine - 1]
]))
```

**Comment by maxbrunsfeld** [comment]
@steelbrain Yeah: don't subtract 1 from `charsInLine` unless you want to omit one character.

**Comment by steelbrain** [comment]
@maxbrunsfeld If I don't subtract 1, then the range is not 0-indexed anymore. The `charsInLine` I get are 1-indexed, like `"asdfghjkl".length === 9`.

**Comment by Arcanemagus** [comment]
@steelbrain the range is [start, end), not [start, end], see [here](https://en.wikipedia.org/wiki/Interval_(mathematics)) for the difference.

@maxbrunsfeld perhaps the documentation can explicitly mention that the end point is exclusive to clear this up for the future?

**Comment by maxbrunsfeld** [comment]
@steelbrain Just think of it as working like `slice` and `substring`.

**Comment by steelbrain** [comment]
@maxbrunsfeld I see now, thank you both for your explanations. I was not looking at it like an interval, I was looking at it like two points. :clap: to @Arcanemagus for explaining this to me on G+
