### ISSUE TITLE
Analytics for actual package usage

### ISSUE THREAD

**Issue by mark-hahn** [atom/atom#9769]
Your'e not going to believe this but I'm going to argue for more analytics. 

If you were to capture actual usage of packages, i.e. hours per day for each package, it would provide several big benefits.  It could be presented in the atom.io package listings.  The ratio of downloads to usage would be particulary useful since it would give a good measure of package acceptance. One sort option could be based on usage.

- It would help users pick packages to try.  Help find out which ones have happy users.
- It would help package developers like me to find out which packages to focus on.  If my package had a bad ratio of downloads to usage I would know to improve it or drop it.

I don't see how this makes privacy any worse.

**Comment by 50Wliu** [comment]
@mark-hahn can you move this over to atom/metrics please?

**Comment by mark-hahn** [comment]
Sure.  Sorry.
