### ISSUE TITLE
Issue with building Atom with node 5.1 and npm 3.4.1

### ISSUE THREAD

**Issue by KamranMackey** [atom/atom#9776]
I am getting an error everytime I try and build Atom with node.js 5.1 and npm 3.4.1. It can't find the "npm-registry client". The issue persists even after a reinstall of npm and node. I'm running Arch Linux.

The error is below.

> Error: Cannot find module 'npm-registry-client'
>    at Function.Module._resolveFilename (module.js:338:15)
>    at Function.Module._load (module.js:289:25)
>    at Module.require (module.js:366:17)
>    at require (module.js:385:17)
>    at Object.<anonymous> (/run/media/kamran/External/Projects/atom/build/node_modules/npm/lib/cache/caching-client.js:9:22)
>    at Module._compile (module.js:425:26)
>    at Object.Module._extensions..js (module.js:432:10)
>    at Module.load (module.js:356:32)
>    at Function.Module._load (module.js:313:12)
>    at Module.require (module.js:366:17)

**Comment by jairovsky** [comment]
I think it's a problem with npm v3.4.1. Take a look: npm/npm#10394

**Comment by maxbrunsfeld** [comment]
I have not tried building Atom with npm 3.4. Can you try with an older version of node/npm?

**Comment by fiws** [comment]
npm@3.5 works (that's npm@next at the time of writing)

**Comment by KamranMackey** [comment]
@maxbrunsfeld seems to be building fine with npm 3.5.0.

**Comment by maxbrunsfeld** [comment]
Ok I'm going to close this out as it seems like it was an npm issue that's been resolved.
