### ISSUE TITLE
Is there a way to disable git feature while running Apm test?

### ISSUE THREAD

**Issue by scv119** [atom/atom#9779]
While running Apm test for a package living in git repository, it tries to load git repro information. This could cause problem if the git repository is huge:

For example, running `apm test` for `atom-helper` in git repository could take 33 seconds:

```
chenshen@chenshen-mbp2:~/.atom/packages/atom-helpers(master)$ apm test
Error Downloading Update: Could not get code signature for running application
[71910:1123/171631:INFO:renderer_main.cc(200)] Renderer process started
[71906:1123/171631:INFO:CONSOLE(46)] "Window load time: 350ms", source: file:///Applications/Atom.app/Contents/Resources/app.asar/static/index.js (46)
....

Finished in 33.654 seconds
4 tests, 16 assertions, 0 failures, 0 skipped

Tests passed
```

where as if we rm `.git` folder and rerun it:

```
chenshen@chenshen-mbp2:~/.atom/packages/atom-helpers$ apm test
[72332:1123/172002:INFO:renderer_main.cc(200)] Renderer process started
Error Downloading Update: Could not get code signature for running application
[72328:1123/172002:INFO:CONSOLE(46)] "Window load time: 333ms", source: file:///Applications/Atom.app/Contents/Resources/app.asar/static/index.js (46)
....

Finished in 0.174 seconds
4 tests, 16 assertions, 0 failures, 0 skipped

Tests passed
```

**Comment by maxbrunsfeld** [comment]
I'm not sure what code is taking so much time. Could you run the tests in an Atom window and record a profile?

**Comment by scv119** [comment]
@maxbrunsfeld  attached is the profile for running following three tests in https://github.com/facebook/nuclide/blob/master/pkg/nuclide/atom-helpers/spec/projects-spec.js
It takes 25 seconds to finished these three tests.

<img width="811" alt="screen shot 2015-12-08 at 12 32 50 am" src="https://cloud.githubusercontent.com/assets/837180/11651130/40b5e624-9d43-11e5-9ba9-5b2e277dbd34.png">



[CPU-20151208T002909.cpuprofile.zip](https://github.com/atom/atom/files/55149/CPU-20151208T002909.cpuprofile.zip)

**Comment by maxbrunsfeld** [comment]
@scv119 Is this the profile after removing the git repository? It shows almost no work being done at all.

**Comment by scv119** [comment]
@maxbrunsfeld no, the profile is the test with .git folder.
