### ISSUE TITLE
rename beta installer 

### ISSUE THREAD

**Issue by tomByrer** [atom/atom#9780]
> The Atom Beta runs side-by-side with the Atom stable release

Though you can't save the installer of both versions in the same folder, since they have the same name.  :fearful:
Perhaps _-beta._ for their file names would help things out?  Sometimes I keep around the file, or transfer to multiple computers via a USB drive; would be nice to know what channel the installer is.

**Comment by izuzak** [comment]
cc @maxbrunsfeld @nathansobo for :thought_balloon:
