### ISSUE TITLE
atom  doese not support socks5 proxy ?

### ISSUE THREAD

**Issue by toplinuxsir** [atom/atom#9781]
atom  doese not support socks5 proxy ?
If support socks5 proxy , how  to  ?
Thanks

**Comment by maxbrunsfeld** [comment]
What feature is not working for you when using the proxy?

**Comment by toplinuxsir** [comment]
such as , atom package install and update etc ....

**Comment by maxbrunsfeld** [comment]
Is this in the Settings View? Or are you using `apm` from the command line?

**Comment by toplinuxsir** [comment]
In the Settings View .

**Comment by toplinuxsir** [comment]
In the Settings View . not using apm form the command line
