### ISSUE TITLE
1.2.4 cmd + r error

### ISSUE THREAD

**Issue by rustanacexd** [atom/atom#9782]
when I press cmd + r in version 1.2.4 this is the error - http://screencast.com/t/IU4HB1oNlwH

**Comment by maxbrunsfeld** [comment]
It looks like there's a file missing from the Atom.app bundle. How did you install Atom? Can you try re-installing it and report whether this still happens to you?

**Comment by rustanacexd** [comment]
I just re installed atom and it is fixed. thanks
