### ISSUE TITLE
Atom Editor Not Responding - Takes up huge bandwidth and crashes my cpu

### ISSUE THREAD

**Issue by erinjerri** [atom/atom#9783]
See screen shot. I'm still not sure why it does this. I tried uninstalling the application and reinstalling it, same problem still occurs. 
![Uploading atom-error.png…]()

**Comment by kylesezhi** [comment]
I have the same issue.

@erinjerri Could you upload your picture again? I can't see it.

**Comment by erinjerri** [comment]
![atom-error](https://cloud.githubusercontent.com/assets/3184381/11377456/a9d4734a-929a-11e5-9cbd-6a0564b29a50.png)

**Comment by kylesezhi** [comment]
Yep, that's the one I get, too. (cool background)

**Comment by benogle** [comment]
@erinjerri what were you doing when this happens? If it's opening a file, can you share the file?

Can you try starting atom in [safe mode](https://atom.io/docs/latest/hacking-atom-debugging#check-if-the-problem-shows-up-in-safe-mode)? Does that fix it?

**Comment by kylesezhi** [comment]
I will try that today and see if the problem persists. Thank you, @benogle !

**Comment by erinjerri** [comment]
It's even just starting up the IDE, it just has that window pop up and
doesn't even run anything. It used to be this way if I were to open up a
file, same issue. It looks like on start it will just freeze up. =(

On Tue, Nov 24, 2015 at 4:50 PM, Kyle Bedell <notifications@github.com>
wrote:

> I will try that today and see if the problem persists. Thank you, @benogle
> <https://github.com/benogle> !
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/atom/atom/issues/9783#issuecomment-159450263>.
>



-- 
Erin Jerri Pangilinan
http://www.erinjerri.com

**Comment by benogle** [comment]
To be clear, you totally killed all atom instances and started atom from the command line with `atom --safe .` in a directory? 

Can you try creating a new directory, then starting atom in that directory? 

```
mkdir newemptydir
atom --safe newemptydir
```

**Comment by apeacox** [comment]
same here. starting with `atom --safe` works without problems.

**Comment by rsese** [comment]
Trying to go through and cleanup some older issues - it's been a while since this report and Atom is currently at release version 1.15.0. I'll go ahead and close the issue for now but if you're still seeing an error with the latest release version of Atom, please feel free to open a new issue and fill out the issue template @erinjerri  @kylesezhi ✌️

**Comment by robomon1** [comment]
For those who find this issue you can turn off the "Automatically download updates" on Mac via the Atom - About Atom menu item in 1.15.0.
