### ISSUE TITLE
Build errors relating to momentary internet connection lapses

### ISSUE THREAD

**Issue by fusion809** [atom/atom#9785]
Hi,

I keep getting errors such as:

``` bash
Unable to download https://www.atom.io/api/packages/language-gfm/versions/0.81.0/tarball: getaddrinfo ETIMEDOUT
```

at the stage of running `script/build`, where the `language-gfm` and `0.81.0` fields varies, according to the apm package the build gets caught at. Sometimes these connection errors also occur at the `Installing build modules` or `Installing apm` stage. Now, I know how to overcome this error when compiling manually from source code by simply re-running `script/build`, but I was wondering if there is any option I can pass to `script/build` that will get it to re-attempt to download and install the package it gets stuck at and then continue on with the build. This would be incredibly helpful for those of us writing ebuilds for Gentoo-based systems such as Sabayon Linux. 

Thanks for your time,
Brenton

**Comment by maxbrunsfeld** [comment]
No, there is no option to `script/build` to retry when a download fails. You just have to run `script/build` again. On the bright side, it won't need to re-download packages whose installation has already succeeded. It would be possible to add some kind of retry logic, but we haven't done that. I'd be open to a PR that adds it, if it doesn't make the script too complicated.
