### ISSUE TITLE
Screen blinks and some parts become dark

### ISSUE THREAD

**Issue by gsavin** [atom/atom#9786]
Hi,

Since a few versions I got a strange problem. I am running Atom 1.2.3 (such a great tool by the way) under Linux (with Gnome3). I will try to describe what happens :

Sometimes, it's like the main view is blinking. For example, if I go to another tab, some white parts will appear for one second at the bottom and the right of my pane.

Furthermore, if I create a new file/folder (yeah it happens sometimes...), when I start typing the name of my new file in the box dialog, this last one will become completly black. It is a bit disturbing :)

I don't know if these two things are linked, but they start happening at the same time. Guess it starts around the 1.2.0 release, but I really not sure. I try to find another issue linked to this one, but my search was not really prolific...

I will keep looking to from source of this troubles, but if anyone has an idea....

Thanks.

**Comment by wyattwmorris** [comment]
Reproduced

**OS: Ubuntu 15.10**
**Atom Version: 1.5.0**

Produced in Safe Mode

Reproduction Steps:  

1. Open Atom in Ubuntu  
2. Open an existing file  
3. Open New Window

Once the third step is executed you should be able to observe the white blinking behavior toward the bottom and around sides of the window.

Reproduced with these steps as well:

1. Open Atom in Ubuntu  
2. Open existing file  
3. Switch File Tab

Was able to capture a screenshot of the behavior:

<img width="1136" alt="screen shot 2016-03-21 at 9 07 07 pm" src="https://cloud.githubusercontent.com/assets/13988512/13939234/9c381838-efa9-11e5-8011-207b88c02313.png">
