### ISSUE TITLE
can atom do find action when I select?

### ISSUE THREAD

**Issue by tangshi** [atom/atom#9787]
`visual studio code` automatically does `find` action when I select something and highlight all found result in both editor window and mini map.

This is such a powerful feature that I really love it. Can `atom` do it or has any package implements this feature?

**Comment by willowsmyth** [comment]
Try selecting the word, followed by Alt+F3.

**Comment by maxbrunsfeld** [comment]
No, we have not implemented this in Atom. There may be a package that does it, but I don't know.

**Comment by 50Wliu** [comment]
This is actually a duplicate of atom/find-and-replace#138, please subscribe there for updates.
