### ISSUE TITLE
Atom windows locks up while sending large file contents to spell-check task

### ISSUE THREAD

**Issue by JohnMurga** [atom/atom#9789]
I sometimes open log files in Atom.
My daily driver is Atom 1.2.x, and it opens everything including some files over 3Mb.
When testing Atom 1.3.x BETA freezes up solid with anything over about 500kb.
Same plugins installed on both versions.
OS tested on is Win 8.1 64Bit, I will test on Ubuntu later.

**Comment by maxbrunsfeld** [comment]
Thanks for the report. I can't reproduce any performance regression with large files on Mac OS. It'd be great to find out if you're seeing this on Ubuntu also.

/cc @raelyard Are you seeing any problems opening multi-megabyte files in the latest Atom?

**Comment by raelyard** [comment]
Not seeing a difference between 1.2.3 and 1.3.0-beta6 on Win 10 or Win 8.1.  On both, when opening a roughly 3 MB file (my test file: http://www.gutenberg.org/ebooks/2600.txt.utf-8) it shows the top of the file quickly and then takes a few seconds before becoming responsive to input.  Sometimes when I try to close Atom after opening the large files, it leaves processes running, but not always.  Same on both of these versions and both of these Windowses.

**Comment by JohnMurga** [comment]
Cannot reproduce on Ubuntu or when running in `--safe` mode.
When using the test file provided by @raelyard I can even get 1.2.4 on Windows to freeze.
However, I do have a stupidly large amount of packages, so I will start going through them to narrow down the cause.

**Comment by maxbrunsfeld** [comment]
You should be able to record a javascript CPU profile to see what's taking so much time.

**Comment by maxbrunsfeld** [comment]
@JohnMurga I'm going to close this out as it looks like a package is causing the slowness. We can reopen if you find that it's an issue with Atom itself.

**Comment by JohnMurga** [comment]
@maxbrunsfeld I did find what was causing the issue
If you try and increase or decrease the editor font size (CTRL-+ or mouse wheel) when you have a huge file loaded (like the example one above), it freezes up for me on Windows (not on Ubuntu).
Fair to assume that Atom is doing something beyond the current viewport on a font size change ?
And whatever it is somehow a little worse under 1.3 than it was on 1.2.
Very much a hedge case, and I have removed what was causing me a problem, but maybe something to be aware of I guess.

**Comment by raelyard** [comment]
Confirmed - seeing same on Windows (did 7, 8.1, and 10).  Changing font size responds slowly (10ish seconds) but doesn't entirely lock up in safe mode.  Without safe mode still not responding after multiple minutes.

**Comment by maxbrunsfeld** [comment]
@JohnMurga Thanks for the info; that's really helpful.

@raelyard could you record a CPU profile of what's going on in safe mode when you change the font size?

**Comment by raelyard** [comment]
@maxbrunsfeld Sorry for the delay - CPU profile attached.

[LargeFileFontSizeChange.cpuprofile.txt](https://github.com/atom/atom/files/53994/LargeFileFontSizeChange.cpuprofile.txt)

**Comment by maxbrunsfeld** [comment]
Thanks @raelyard. That narrows it down quite a bit.

**Comment by maxbrunsfeld** [comment]
Looks like [sending the buffer contents to the spell-check task](https://github.com/atom/spell-check/blob/4d87c10686eea05c7290e187cd26d027b2bef33c/lib/spell-check-view.coffee#L72) is taking multiple minutes for some reason.

**Comment by raelyard** [comment]
Tried OSX - only happening on Windows.

**Comment by JohnMurga** [comment]
I am not seeing this in 1.7.0-beta0, has the behavior changed ?
Maybe this can now be closed ...
