### ISSUE TITLE
Editor font size not correct on Mac OS X

### ISSUE THREAD

**Issue by cle1109** [atom/atom#9790]
I set my editor font to Menlo Regular 11pt, which I also use in other programs such as Terminal.app. However, the font is rendered too small in Atom as compared to how it should be (see screenshot, the bottom row shows the correct font size rendering in Terminal.app, whereas the top row shows how the same font is rendered in Atom).

![font-atom](https://cloud.githubusercontent.com/assets/4377312/11367963/53e16368-92b7-11e5-9062-dacda6ddf766.png)

**Comment by maxbrunsfeld** [comment]
Yeah, the horizontal spacing is different. Atom has them spaced wider apart. I'm not sure what controls that.

/cc @as-cii @nathansobo Do you know if there's a CSS rules that @cle1109 could set to control that?

**Comment by cle1109** [comment]
I'm not sure it's only the horizontal spacing. The characters look smaller overall to me.

**Comment by maxbrunsfeld** [comment]
Could you share an image where you zoom into both and measure them? I can't tell that their heights or widths are different.

**Comment by cle1109** [comment]
Yes, you're right. The text color in Atom is not black like in Terminal.app, that's why the characters look slightly different, but they are just wider apart.

**Comment by alexhicks** [comment]
You should be able to change the kerning using `letter-spacing: 0.1px` in your stylesheet. 
I'd have a play to see what makes it look good for you.

**Comment by maxbrunsfeld** [comment]
Thanks @alexhicks. @cle1109 I'm going to close this out, as I don't think it's a bug. Please let me know if you have any more problems.

**Comment by cle1109** [comment]
Great, thanks @alexhicks! A value of 0.37px corresponds to the/my system settings (at least approximately). Isn't it possible to get that value from the system? It would be nice if Atom had fonts that looked identical to what other (native) apps use though.

**Comment by alexhicks** [comment]
Letter-spacing if not set should use the font default. 

But I've been messing around with chrome, atom and Terminal. It appears the OSX system displays the font differently than the browsers. I don't know why exactly. But when comparing between sublime and terminal there were no differences.  But for you the settings that get you the closest to Terminal would be setting the font height in atom to 8 

So I'd conclude that its an issue with how the browsers render the font differently to the OSX system. Which one is doing it correctly its not my place to say :)

Terminal (black with white text) vs chrome:
![image](https://cloud.githubusercontent.com/assets/7707452/11395151/7dd2b06c-93bd-11e5-96af-4c9b29ad52b2.png)


Terminal (black with white text) vs atom:
![image](https://cloud.githubusercontent.com/assets/7707452/11395165/94e62478-93bd-11e5-8e16-5448992c3d94.png)

Terminal (black with white text) vs Sublime text 3:
![image](https://cloud.githubusercontent.com/assets/7707452/11395103/277706f0-93bd-11e5-96dc-06d52f7eff5e.png)

**Comment by as-cii** [comment]
On a side note, I wonder if setting the `text-rendering` to some other values (e.g. `optimizeLegibility`, `geometricPrecision`, etc.) allows to mimic the OS default behavior.

**Comment by cle1109** [comment]
@alexhicks I would argue that since Terminal and Sublime are native OS X apps, they render fonts correctly (or at least, this should be the baseline how fonts should be rendered in order to be consistent). Both Chrome and Atom use an alternative approach to rendering text (because I guess they want to be cross-platform among other reasons). Did you try how Safari (a native OS X app) renders text?

@as-cii it would be great if there was a setting that corresponds to the default OS behavior!

**Comment by alexhicks** [comment]
@as-cii I did try text-rendering, it didn't appear to have any effect at that font size.

@cle1109 Safari does the same thing:
![image](https://cloud.githubusercontent.com/assets/7707452/11395635/4e200f10-93c0-11e5-91a5-27ff62bfa54a.png)

Looks like its a web text rendering issue thats systematic.
