### ISSUE TITLE
'linter-eslint' package version appeared as 'undefined' in Settings|Packages (after Atom auto-update I think) and I had to uninstall and re-install that package to make it work again

### ISSUE THREAD

**Issue by darkred** [atom/atom#9793]
Using Atom 1.3.0 beta 6 in win10 x64.
The installed packages are `linter-eslint 5.2.4` `autoupdate packages`, `language-batchfile` `jshint`(disabled) and `linter` ([screenshot](https://i.imgur.com/s5af0ea.jpg)).

The problem is that `linter-eslint` package version today appeared as "undefined" in Settings|Packages.
(Unfortunately I didn't keep a screenshot of that)
I noticed that because the package was not working, though it was enabled.

Disabling and re-enabling it didn't fix it. 
What only fixed it (i.e. made the package work, and display it's version number instead of "undefined") was uninstalling+re-installing the package.
But, this works only until the next Atom update_(I think that it occurred after updating Atom from beta 5 to beta 6)_

This is the 2nd time this occurs the last days (both cases were after an Atom update I think) and in both cases I had to uninstall and re-install it.

I didn't find any relevant entry in Developer Tools|Console
Also,I don't have such issues with the other packages.
<br>

Thank you

**Comment by maxbrunsfeld** [comment]
Thanks for the report. Could you reopen this issue on the [https://github.com/atom/settings-view](settings-view] repo?

**Comment by darkred** [comment]
Ok, I just did.
