### ISSUE TITLE
how do I find the version of electron and node in atom?

### ISSUE THREAD

**Issue by mark-hahn** [atom/atom#9800]
apm -v doesn't help.  It is showing a really old version of node.  I need this to research the problem at #9555.

Also, where can I download atom v1.1.0?  That is the most recent version I can use because of #9555.

**Comment by maxbrunsfeld** [comment]
To find out the versions of node, electron, chrome etc, run this in your JS console:

```js
process.versions
````

**Comment by mark-hahn** [comment]
I also need to download atom 1.1.0.  Where can I find that?

**Comment by 50Wliu** [comment]
https://github.com/atom/atom/releases/tag/v1.1.0

**Comment by mark-hahn** [comment]
thx
