### ISSUE TITLE
After running script\build I get common.gypi not found

### ISSUE THREAD

**Issue by Gela** [atom/atom#9804]
And then all the consequent gyp related steps fail as well. I added GYP_MSVS_VERSION='2015' to the list of my env variables since I am running VS 2015. I know there has been a couple other issues similar to this but none of them offered a solution for my issue unfortunately.

I am using:
Python 2.7.10
Node.Js 4.2.2
OS: Windows 8.1 64-bit 
x86

Screenshot below:
![err](https://cloud.githubusercontent.com/assets/3746552/11388203/75b556c6-9301-11e5-8635-07968b5eebe0.JPG)

**Comment by BrainCrumbz** [comment]
On a Windows 10 64 bit machine with both Visual Studio 2013 and 2015 Community Ed. `%GYP_MSVS_VERSION%=2013`. `.\script\build --install-dir ..\temp\install` returns some errors. The full output is pasted [here](http://pastebin.com/Wsyz8YBD). Last first block is:

```
Installing build modules...
gyp: C:\Users\giuseppe\.node-gyp\4.2.2\common.gypi not found (cwd: D:\WS\atom\atom\build\node_modules\runas) while reading includes of binding.gyp while trying to load binding.gyp
gyp ERR! configure error
gyp ERR! stack Error: `gyp` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onCpExit (D:\WS\atom\atom\build\node_modules\npm\node_modules\node-gyp\lib\configure.js:357:16)
gyp ERR! stack     at emitTwo (events.js:87:13)
gyp ERR! stack     at ChildProcess.emit (events.js:172:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:200:12)
gyp ERR! System Windows_NT 10.0.10240
gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "D:\\WS\\atom\\atom\\build\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild"
gyp ERR! cwd D:\WS\atom\atom\build\node_modules\runas
gyp ERR! node -v v4.2.2
gyp ERR! node-gyp -v v2.0.2
gyp ERR! not ok
```

**Comment by BrainCrumbz** [comment]
Possibly related to this unsolved [node-gyp issue](https://github.com/nodejs/node-gyp/issues/629) on Windows, and quite a number of similar ones.

**Comment by thedaniel** [comment]
If you install C++ build tools (per this comment) can you successfully build? https://github.com/nodejs/node-gyp/issues/629#issuecomment-153196245

**Comment by BrainCrumbz** [comment]
The 1st mentioned step in that comment is to Install VC++ Build Tools Technical Preview, and the comment starts mentioning "without having Visual Studio installed on your computer".  
Is that first step needed even if one already has Visual Studio installed?

**Comment by damieng** [comment]
Are you using the GitHub for Windows shell? If so that will be the problem.

That shell has an older version of MSBuild in the path it provides which is incapable of understanding the VS2015 options.

You should simply be able to open a PowerShell command and do it from there (make sure you have a git command somewhere in your system path).

I have updated the Windows build docs to reflect this https://github.com/atom/atom/blob/d95f1b140554a262e1bd4f07f80bf3ce8d089f82/docs/build-instructions/windows.md

**Comment by BrainCrumbz** [comment]
Yes, I think I was using GitHub for Windows shell, so we'll try that again. Thanks for the update.
