### ISSUE TITLE
Scrollbar and file position don't match

### ISSUE THREAD

**Issue by pyvim** [atom/atom#9806]
Hello there.

After start Atom with last project scroll is up, but redactor position different.

Atom 1.2.4.

Screenshot:
![2015-11-25 11 09 18](https://cloud.githubusercontent.com/assets/4338636/11391699/756ec01c-9365-11e5-9d26-3c77adfc546c.png)

**Comment by lee-dohm** [comment]
Do you mean that you're scrolled to the end of the file, but the scroll thumb appears to be at the top?

**Comment by pyvim** [comment]
No.
I open Atom. Automatically loaded my last project. In few tabs scroll thumb be at the top, but file is scrolled. Scroll thumb not equals file position. I do nothing.

Sorry for my bad English.

**Comment by 50Wliu** [comment]
I think I've encountered this before:
1. Open a file
2. Scroll down a bit
3. Reload Atom (or update the file externally)
4. Observe that the scrollbar is in the wrong position (or alternatively, the file)

Windows 10 x64, Atom 1.4.0-dev-f159e81

**Comment by Morosko** [comment]
I have the exact same behaviour on Arch Linux (4.2.5-1-ARCH x86_64) with Atom 1.2.4.

**Comment by fruggiero** [comment]
Same behaviour in 1.3.1  even without reloading the entire project.
Reopening a file is enough.
How to reproduce:

-Open a project
-Open a file in the project and scroll to the bottom
-Close the file
-Reopen the file

Now the scrollbar is at the top, but the view isn't

**Comment by cynicaldevil** [comment]
I can work on this bug if someone can give me some guidelines/tips. Newbie here!
