### ISSUE TITLE
Regex Search and Replace

### ISSUE THREAD

**Issue by husni** [atom/atom#9807]
Bug found when using regex on Atom:

Input string (in the Editor)
```
test123
```

Search & Replace using regex
Find: `(.*)`
Replace: `$1x`

Result:
```
test123xx
```

Expected:
```
test123x
```

**Comment by lee-dohm** [comment]
Would you mind re-opening this on the [find-and-replace package](https://github.com/atom/find-and-replace)? That's the repo where this functionality is located.

Thanks for reporting! I was able to confirm the issue using Atom v1.4.0-dev-508e8b0 on Mac OS X 10.11.1.

**Comment by husni** [comment]
@lee-dohm Thanks, moved here: https://github.com/atom/find-and-replace/issues/605
