### ISSUE TITLE
Can't make a script called 'atom' that runs atom-beta

### ISSUE THREAD

**Issue by ChrisJefferson** [atom/atom#9811]
I want to:

* Use atom-beta as my standard atom
* Have atom-stable installed, just in case atom-beta has a bad release.

In particular, I want to be able to start atom-beta from the command line with the command `atom`, but the script assumes you want to run `atom`, unless `atom-beta` is called exactly `atom-beta`.

Would it be reasonable to switch to using the fact that `atom` and `atom-beta` are symlinks into the own directories, and follow that instead?

Or would it work if I renamed `atom.app` to `atom-stable.app` and `atom-beta.app` to `atom.app` or would that confuse something else?

**Comment by AEgan** [comment]
you could use bash aliases
Right now I use `atomb` for atom beta
```
alias atomb="atom-beta"
```

**Comment by jtokoph** [comment]
Old issue but found a solution that works for me. I conditionally set an alias if atom-beta exists in my path:

```bash
if [[ `which atom-beta` ]]; then
  alias atom='atom-beta'
fi
```

If you want to temporarily use stable atom, then prefix your atom command with a slash like so:

```bash
$ \atom some-file-to-edit-in-stable.txt
```

That will bypass your alias.

**Comment by lee-dohm** [comment]
I think @jtokoph's solution is probably the cleanest. I use aliases myself ... `a` for stable Atom and `ab` for beta Atom. Let us know if that doesn't answer your question!
