### ISSUE TITLE
Request : Editor Vertical Scrollbar pull at the right side without padding

### ISSUE THREAD

**Issue by pantuts** [atom/atom#9814]
Atom Editor
Version: 1.3.0-beta6-235a1a5
OS: Manjaro Linux x86_64

I've tried to edit the user stylesheet so that the vertical scrollbar of the editor will be at the very right side without having padding, but did not get it. Currently the editor when maximized, there is a padding on the right side of the scrollbar.

This issue is for enhancement for the editor vertical scrollbar to remove its padding when user maximizes the editor and the scrollbar is present.

![selection_021](https://cloud.githubusercontent.com/assets/894185/11398019/c3680cd0-93b8-11e5-9429-a2d0768fb73d.png)

Thanks.

**Comment by lee-dohm** [comment]
Are you suggesting that this change should be made for all themes and all users? Or are you asking how to make this work?

/cc @simurai

**Comment by pantuts** [comment]
I think this should be on the user settings.

**Comment by simurai** [comment]
@pantuts What's the theme you are using?

If it's One dark, you can switch between `Spacious` and `Compact` mode in the theme settings.

![padding](https://cloud.githubusercontent.com/assets/378023/11414210/f22bafa4-9435-11e5-9924-b0e2e7e56335.gif)

Compact mode shouldn't have any padding after the scrollbar.

**Comment by pantuts** [comment]
@simurai may i know your version please? I can't find similar settings.

**Comment by simurai** [comment]
I'm on the `1.4.0-dev`, but it should be in Atom stable.

Note that it's not in the "normal" Settings, but in the "theme settings".

1. Click on `Themes`
2. Click on the "settings" icon next to the theme picker.

![screen shot 2015-11-26 at 3 36 09 pm](https://cloud.githubusercontent.com/assets/378023/11416761/09511264-9454-11e5-98c6-6f068fe6ca4c.png)

**Comment by pantuts** [comment]
Oh my, my mistake. It's here. Also the padding was gone. Thanks @simurai ! Will close this! :)
