### ISSUE TITLE
Github Markdown renderer is different to actual Github output

### ISSUE THREAD

**Issue by axic** [atom/atom#9818]
The below sample markdown renders the numbers without restarting in Atom, while on Github (here) the third point will restart from 1. Perhaps it is an edge case I should rely on. Not sure which renderer is correct, but I like the output from Atom :)

1. test

2. test
```
hello
```

3. test

**Comment by mnquintana** [comment]
Would you mind reopening this on https://github.com/atom/markdown-preview? Thanks!
