### ISSUE TITLE
Proposal: Block Decorations

### ISSUE THREAD

**Issue by as-cii** [atom/atom#9819]
The aim of this document is to write down some of the ideas @nathansobo and I discussed over the past days. I don't think we should implement everything herein proposed in one single, big step. Still, I feel like it's valuable to have a place to discuss the API and to share these ideas with the :globe_with_meridians:.

As of today, Atom doesn't provide a way to create decorations that affect screen rows layout. More specifically, we think it would be :cool: to expose an API that allows users to create something like the following:

![block-decorations](https://cloud.githubusercontent.com/assets/482957/11395769/301ee8cc-936d-11e5-9323-1b376d39f1e9.jpg)

You can notice how lines of text break when a block decoration begins and how they resume later when the decoration ends. This hypothethical abstraction would cover several scenarios for package authors, among which:

* Show diffs;
* Show previews;
* And, more generally, provide a richer experience within the editor;

This primitive would cover only decorations in between screen rows; that is, users won't be able to insert inline elements between `<span>`s inside a screen row by using a block decoration.

## API

The code for using this API could look like the following:

```js
let div = document.createElement("div")
let marker = editor.markScreenPosition([7, 0], {invalidate: "never"}) // is "never" the right invalidation strategy?
let decoration = editor.decorateMarker(marker, {type: "block", item: div})
```

I am also thinking to provide a shorthand for the above code:

```js
editor.addBlockDecorationBeforeScreenRow(7, document.createElement("div"))
```

But I guess I'd like to see how this gets used before dealing with this kind of extra details, although I prefer the latter version more in terms of readability. :book:

Also, I feel like we might take this a bit further by enforcing a better separation of concerns between the model and the view, by avoiding to pass an element as the `item` when decorating the marker and using the `ViewRegistry` instead. This seems to stray from how we implemented other decoration APIs, so take this thought with a grain of salt.

### Performance

We would need to know the whole content height in advance in order to show the appropriate vertical scrollbar. Right now, we measure a dummy line's height and calculate `dummyLineHeight * model.getScreenLineCount()`; if we introduced this kind of custom content, however, we'd need to measure block decorations upfront and then calculate height like: `dummyLineHeight * model.getScreenLineCount() + measuredBlockDecorationsHeight`. When having lots of these, loading/refreshing them could become problematic.

On the core side, the scrollbar problem _seems_ the only issue preventing block decorations to be fetched, rendered and measured incrementally (as we do for other decorations); we might even argue that people are used to this sort of progressive content loading on the web, thus making this a non-problem but I'd :heart: to have some more feedback on this. For example, what about minimap? I would think that it will need to know block decorations' height in advance rather than as the user scrolls.

Another optimization tactic we could employ is to split up the measurement tasks in chunks to be executed across multiple animation frames.

To tell the truth, I believe we should just go for the "measure everything upfront" approach first, see how that feels and then re-iterate on that later (if needed). :racehorse: 

### Styling

Because of Shadow DOM, we will have to insert elements outside the shadow root and find a way to teleport them in the right spot inside the editor content. The most straightforward way of doing this could be the following:

```html
<atom-text-editor>
  <#shadow-root>
    <div class='tile-1'>
      <content select=".block-decoration-before-screen-row-1"></content>
      <div data-screen-row='1'></div>
      <div data-screen-row='2'></div>
    </div>
    <div class='tile-2'>
      <div data-screen-row='3'></div>
      <content select=".block-decoration-before-screen-row-4"></content>
      <div data-screen-row='4'></div>
    </div>
  </#shadow-root>

  <div class='block-decoration-before-screen-row-1'></div>
  <div class='block-decoration-before-screen-row-1'></div>
  <div class='block-decoration-before-screen-row-4'></div>
</atom-text-editor>
```

### UX

When a block decoration above the current scroll area changes its height, we need to make sure to adjust the current scroll position seamlessly, so that the editor doesn't scroll down when the user is, for example, editing something.

**Question:** What about the gutter? Should we have block decorations in there as well?

### Naming

Should we consider other names for this API? "Block decoration" seems a pretty sensible choice to me, as it seems to reflect CSS' semantics for elements with a `display: block` style. What do you think? :bulb:

Feedback is super welcome! :sparkles: :bow:

/cc: @nathansobo @maxbrunsfeld @atom/feedback

**Comment by simurai** [comment]
:heart_eyes: Packages like https://atom.io/packages/quick-editor would benefit a lot.

**Comment by benogle** [comment]
:+1: Also https://atom.io/packages/merge-conflicts, and nuclide, and probably 1000 other things.

**Comment by mauricioszabo** [comment]
Can't :+1: enough this proposal!

I'm trying to make a package to do "quick commits" and other git commands in Atom in a unubtrusive way, and also to show diff from one specific file in all its commits. Right now, I'm creating a "read-only" view and hard-wiring things, using "ObserveElement" and other tricks to hide line numbers from some places and change line number from others. This would remove all this magic!

**Comment by mikeball** [comment]
:+1: Yes, this would be a great feature! I would like to build a package that does inline evaluation similar to LightTable. See https://discuss.atom.io/t/inline-evaluation-lighttable-swift-style/12221/12 for some additional discussion. Also https://github.com/JunoLab/atom-ink would benefit a lot as well.

**Comment by rgbkrk** [comment]
Thank you so much, really looking forward to this for Hydrogen, script, and other REPL packages.
