### ISSUE TITLE
OSX: open windows list disappeared

### ISSUE THREAD

**Issue by emirotin** [atom/atom#9823]
I usually have 3 to 8 open Atom windows with different projects, and used to switch between them with the Window menu that used to list all the open windows. Recently it just stopped working - only shows generic options: Minimize, Zoom, Bring all to front.

Atom 1.2.4
OSX 10.11.1

**Comment by amytruong** [comment]
I've been able to reproduce this bug. Thanks for reporting!

**Comment by benogle** [comment]
This has been fixed on 1.3 beta. Download the [beta](http://atom.io/beta) to get the fix.
