### ISSUE TITLE
Inconsistencies in Menu Items

### ISSUE THREAD

**Issue by ghostlion88** [atom/atom#9828]
I have noticed two inconsistencies in menu items.
The first is under View->Toggle Tree View. The hotkey for this menu item is labelled 'Ctrl+Backslash' This goes against the adopted convention of hotkey labels that are usually like 'Shift+Ctrl+=' instead of 'Shift+Ctrl+Equals' or 'Shift+Ctrl+-' instead of 'Sift+Ctrl+minus'.
The second inconsistency is the same idea as the first, and is under Selection->Single Selection. The hotkey is labelled 'Escape', while the key on the keyboard is labelled 'Esc'.

**Comment by 50Wliu** [comment]
What OS are you on?

**Comment by ghostlion88** [comment]
Atom version is 1.3.0-dev-516d6ed
OS is Ubuntu 12.04.5 LTS
