### ISSUE TITLE
Confusing Tip When Atom is Opened

### ISSUE THREAD

**Issue by ghostlion88** [atom/atom#9829]
When I open Atom and have no tabs open, tips are displayed to me and change every few seconds. One of the tips is "You can split a pane with 'Ctrl + K Right'". I'm not sure what the 'Right' here means. Perhaps better wording should be adopted.

**Comment by 50Wliu** [comment]
Literally, the right arrow key.

Again, what OS are you on, and what Atom version?

**Comment by ghostlion88** [comment]
Atom version is 1.3.0-dev-516d6ed
OS is Ubuntu 12.04.5 LTS
