### ISSUE TITLE
When creating a new file, atom doesn't allow to enter a file name

### ISSUE THREAD

**Issue by fmaida** [atom/atom#9832]
I'm trying to create a new file inside a folder but I'm unable to do so because Atom doesn't allow me to enter a file name for it. I'm actually testing Atom Beta v1.3.0-beta6 on Mac OS X 10.11.1.

This is what I'm doing :

1) I move the mouse pointer over a folder in the tree-view of atom
2) I right-click and choose "New file" from the pop-up menu
3) A pop-up box appears on the upper center of the Atom window, asking me to enter the path to the new file
4) I move the cursor over the pop-up box and the mouse pointer changes to the edit mode. However when I click on it and I try to write with the keyboard, nothing happens.
5) After a 10-20 seconds, a pop-up window appears with this message: "EDITOR IS NOT RESPONDING - The editor is not responding. Would you like to force close or just keep waiting?"

Here's a screenshot of what I see on my computer:

![index_jade_-__users_scala_documents_progetti_progetti_html-css_promo_allascala_it_-_atom](https://cloud.githubusercontent.com/assets/605017/11420309/9b3d3e5e-942d-11e5-9a70-42c67909b038.jpg)

![index_jade_-__users_scala_documents_progetti_progetti_html-css_promo_allascala_it_-_atom](https://cloud.githubusercontent.com/assets/605017/11420404/34ca2f3c-942e-11e5-9298-65e3da8c5229.jpg)

**Comment by izuzak** [comment]
Thanks for the detailed report, @fmaida, but I'm having trouble reproducing this.

Can you reproduce this on an older version of Atom (e.g. 1.2.4)? Also, can you reproduce this when you start Atom from any folder and when you create that file in any folder, or does it happen only for some folders? And can you reproduce this in safe mode? 

https://github.com/atom/atom/blob/master/CONTRIBUTING.md#reporting-bugs

**Comment by fmaida** [comment]
I never had that issue before with Atom, yesterday was the very first time I had this problem. After closing and reopening Atom I have created another two files and I had no problems. 
When I read your request I have tried to remove the writing permission from the folder and to create two different files at once in two different instances of Atom, but in both cases Atom behave correctly. I honestly have no idea of what I could try to reproduce this issue again.

**Comment by rsese** [comment]
Trying to go through and cleanup some older issues - it's been a while since this report and it looks like it wasn't reproducible.  Going to go ahead and close for now, thanks again for reporting :v:

**Comment by hebronwatson** [comment]
Having the same issue. I cannot open a new file in my working project directory using the dropdown.
Meaning, I cannot name a new file and save it to my current project. However, I can create a new file, then save it in my current project directory and of course it shows up fine. This is not easily reproducible. I think that something goes wrong inside of atom to cause this, as it worked fine before about a week ago.

![image](https://user-images.githubusercontent.com/18713831/32389377-ab0bd2ae-c087-11e7-8f01-e25afe87525f.png)

**Comment by hebronwatson** [comment]
having same issue, and also cannot rename

**Comment by rsese** [comment]
@hebronwatson can you open a new issue and fill out the issue template?  In particular, please let us know if you can reproduce in safe mode.
