### ISSUE TITLE
Adding new-line bind in keymap.cson not working

### ISSUE THREAD

**Issue by pobri19** [atom/atom#9833]
I've added a bind for shift+enter in my keymap.cson, but when I press shift+enter in my code files nothing happens. Added it like so:

    'atom-text-editor':
      'shift-enter': 'editor:new-line'

I checked the "Key Binding Resolver" (ctrl+.) and pressed shift-enter and it says:

editor:new-line, atom-text-editor, /home/me/.atom/keymap.cson

The line is green, has a tick beside it, and it says "No issues".

Any ideas?

**Comment by izuzak** [comment]
@pobri19 Can you share the full contents of your keymap.cson file, a screenshot of what the keybinding resolver shows when you hit shift+enter, the version of Atom you are using, and the OS+version you're on? Also, just to make sure, reloading Atom after you've modified keymap.cson doesn't change anything? Thanks

**Comment by pobri19** [comment]
@izuzak No problem, full contents is exactly what's above, I haven't got any other binds. Screenshot:

![screenshot from 2015-11-26 20 19 50](https://cloud.githubusercontent.com/assets/721274/11420653/2b692450-947b-11e5-8873-f8746aba0778.png)

I'm using Atom 1.2.4 and Linux Mint 17 Cinnamon 64-bit

Thank you :)

**Comment by izuzak** [comment]
Does using `newline` instead of `new-line` help? :smile: There's no `editor:new-line` command, only `editor:newline`.

**Comment by pobri19** [comment]
That did it! Thanks, I'm an idiot :( Haha. Appreciate your help.

**Comment by izuzak** [comment]
Ha, no worries -- it's really hard to spot problems like these. I think there's an open issue somewhere to improve that (so that you're warned that the command doesn't exist) but can't find it right now.
