### ISSUE TITLE
When creating a new file, atom doesn't allow to enter a file name

### ISSUE THREAD

**Issue by fmaida** [atom/atom#9834]
**EDIT:**

I closed Atom Beta and then relaunched it, and the issue was gone. So if you want you can close this thread and mark it as resolved, thanks.

----

I'm trying to create a new file inside a folder but I'm unable to do so because Atom doesn't allow me to enter a file name for it. I'm actually testing Atom v1.3.0-beta6 on Mac OS X 10.11.1.

This is what I'm doing :

1) I move the mouse pointer over a folder in the tree-view of atom
2) I right-click and choose "New file" from the pop-up menu
3) A pop-up box appears on the upper center of the Atom window, asking me to enter the file name
4) I click over the pop-up box but when I try to write with the keyboard nothing happens.
5) After a 10-20 seconds, a pop-up window appears with this message: "EDITOR IS NOT RESPONDING - The editor is not responding. Would you like to force close or just keep waiting?"

Here's a screenshot of what I see on my computer:

![index_jade_-__users_scala_documents_progetti_progetti_html-css_promo_allascala_it_-_atom](https://cloud.githubusercontent.com/assets/605017/11420530/f10c25e2-942e-11e5-8443-0dfeb69184c8.jpg)

![index_jade_-__users_scala_documents_progetti_progetti_html-css_promo_allascala_it_-_atom](https://cloud.githubusercontent.com/assets/605017/11420536/f6a55c08-942e-11e5-9843-6c8cacc34fad.jpg)

**Comment by 50Wliu** [comment]
I'm going to close this, but if you see this issue again, please comment here so we can re-open it!
