### ISSUE TITLE
Cannot test newly created package

### ISSUE THREAD

**Issue by mertkahyaoglu** [atom/atom#9837]
When I try to run package specs, I get `Error: Cannot find module fs-plus/underscore-plus`. If I install those packages manually and try `apm test` from console, then I get;

`registerProtocol API has been replaced by the register[File/Http/Buffer/String]Protocol API family, please switch to the new APIs.` coming from `electron/protocol.coffee`. Am I testing my package wrong or something? What should I do?

OSX Yosemite
Atom 1.2.4

**Comment by 50Wliu** [comment]
> If I install those packages manually

How did you install those?  `npm install` or `apm install`?  If the former, please remove the `node_modules` folder and execute `apm install` instead.

**Comment by mertkahyaoglu** [comment]
@50Wliu I installed using `apm install`.

**Comment by mertkahyaoglu** [comment]
Any help on this? I can't test my package :disappointed:

**Comment by 50Wliu** [comment]
What package are you trying to test?  Are you testing through the Atom UI or `atom --test spec`/`apm test`?

**Comment by mertkahyaoglu** [comment]
I created a package, wrote some specs and trying to test it. None of the options that you said are working. I tried it from Ubuntu, there is no problem.
