### ISSUE TITLE
Atom crashes when closing a full screen window

### ISSUE THREAD

**Issue by twsh** [atom/atom#9838]
I'm running Atom 1.2.4 on OSX 10.11.1. The following steps cause a crash:

1. Open an Atom window full screen
2. SHIFT + CMD + W

**Comment by 50Wliu** [comment]
This has already been fixed on master and will *probably* be out in the next patch release, 1.2.5.

**Comment by OmgImAlexis** [comment]
@50Wliu any idea on a rough ETA for the next release? I only use Atom and it's getting annoying with it losing my work because of this. :disappointed:

**Comment by 50Wliu** [comment]
@OmgImAlexis I don't work at Github, so unfortunately I can't offer an ETA.  Sorry :(.

**Comment by twsh** [comment]
This still happens with 1.3.0.

**Comment by jmeas** [comment]
Ping @50Wliu . Still a problem with 1.3.2.

**Comment by 50Wliu** [comment]
> Still a problem with 1.3.2.

It's actually slated for the 1.4.0 release right now (the fix was merged into master during Atom 1.2, so that it skipped the 1.3 betas and got targeted for 1.4-dev).  I'll try to open a PR to backport the fix tomorrow though; we'll see how that goes.
