### ISSUE TITLE
Open involuntary new window when dragging in a file

### ISSUE THREAD

**Issue by lczech** [atom/atom#9846]
Whenever I drag a file from the file brower (nautilus on ubuntu), atom opens a new window. This seemed to have changed now that I updated from 1.1.0 to 1.2.4. There have been issues like this before (https://github.com/atom/atom/issues/2005 and https://github.com/atom/atom/issues/1722), but this one seems a bit different:
- Files from outside of the current project directory open in a new window. If I close this new window again, then drag another file from that same directory (still outside of the project directory) into the original window, again a new window opens, but this time with the file that I just dragged AND the one that I dragged before (and closed again). So it seems, atom is internally creating something like a project and stores which files were opened from that directory.
- Even more interestingly, something similar happens when dragging files from the current project directory: A new window is opened for this file, too, but it also contains all the files that were open in the original window. Thus, I get a copy of the original window.

Working with
atom 1.2.4
ubuntu 14.04

**Comment by 50Wliu** [comment]
@izuzak, @mnquintana you two have been keeping pretty up-to-date with these window issues - is this a duplicate of another issue or a new bug?

**Comment by lee-dohm** [comment]
Detailed information on what appears to be the same issue (though on Windows) here:

https://discuss.atom.io/t/dragn-dropping-from-explorer-opens-a-new-atom-window/22893

**Comment by lczech** [comment]
Yep, this sounds exactly the same. And there even is a pointer to some problematic code ;-)
Thanks @lee-dohm!

**Comment by lee-dohm** [comment]
You're welcome. I'm glad I could help! :grinning:

**Comment by ronilaukkarinen** [comment]
:+1: here.

I can confirm this, using OS X 10.11.1 and Atom 1.2.4. You should be able to drag *any* file to opened window without new window spawning. Very annoying.

**Comment by albinekb** [comment]
:+1: this is very annoying and keeps me from loving Atom.

**Comment by Lordmau5** [comment]
I'll drop in on this. Having the exact same issue.
Sometimes it works, sometimes it doesn't.
It's really annoying

**Comment by jsieler** [comment]
That long and still open?! Wonder if someone cares about opened issues at all if i see them...

**Comment by jsieler** [comment]
Same here.

**Comment by mikecon94** [comment]
Agreed. I think it should be an option for the user to decide whether to open "new" files are opened in a new tab or a new window.

**Comment by albinekb** [comment]
Switched to VS Code and this problem didn't exists there so 👍
