### ISSUE TITLE
A pane is still visible when closing its last tab. Bug or correct behaviour?

### ISSUE THREAD

**Issue by fmaida** [atom/atom#9854]
I'm using Atom Beta v1.3.0-beta6 on Mac OS X 10.11.1, but I'm actually getting the same results on Atom v1.2.3

1) I split the editor area in two panes by choosing VIEW -> PANES -> SPLIT UP:

![panes_e_view_e_menubar](https://cloud.githubusercontent.com/assets/605017/11451228/f9137c00-95bd-11e5-8e24-18e38ddded31.jpg)

2) Then I close the only tab opened on the lower pane ("index.jade"):

![index_jade_-__users_scala_documents_progetti_progetti_html-css_promo_allascala_it_-_atom 2](https://cloud.githubusercontent.com/assets/605017/11451230/158a521e-95be-11e5-8a6b-fde11918290b.jpg)

3) The lower pane then is still visible, even if it's empty:

![_users_scala_documents_progetti_progetti_html-css_promo_allascala_it_-_atom](https://cloud.githubusercontent.com/assets/605017/11451237/3dc54a22-95be-11e5-8f90-6ee715bd60e4.jpg)

This is the log taken from console.app :

```
28/11/15 10:06:17,642	Atom[770]	App load time: 1211ms
28/11/15 10:06:39,212	Atom[770]	BUG in libdispatch client: kevent[EVFILT_MEMORYSTATUS] add: "Operation not supported" - 0x2d
28/11/15 10:06:40,301	Atom[770]	assertion failed: 15B42: libxpc.dylib + 79134 [3E09C275-A33B-357A-B0AB-A2DDF88EC9D5]: 0x89
28/11/15 10:19:15,243	Atom[909]	App load time: 1536ms
28/11/15 10:19:40,495	Atom[950]	App load time: 363ms
28/11/15 10:23:19,103	Atom[983]	App load time: 2064ms
28/11/15 10:27:02,212	Atom[1031]	App load time: 350ms
28/11/15 10:35:24,418	Atom[1031]	BUG in libdispatch client: kevent[EVFILT_MEMORYSTATUS] add: "Operation not supported" - 0x2d
28/11/15 10:35:24,574	Atom[1031]	assertion failed: 15B42: libxpc.dylib + 79134 [3E09C275-A33B-357A-B0AB-A2DDF88EC9D5]: 0x89
28/11/15 10:35:29,070	Atom[1031]	Cannot read property 'length' of undefined
28/11/15 10:35:29,075	Atom[1031]	TypeError: Cannot read property 'length' of undefined
    at AtomApplication.<anonymous> (/Applications/Atom Beta.app/Contents/Resources/app.asar/src/browser/atom-application.js:608:40)
    at AtomApplication.module.exports.AtomApplication.openPaths (/Applications/Atom Beta.app/Contents/Resources/app.asar/src/browser/atom-application.js:613:10)
    at /Applications/Atom Beta.app/Contents/Resources/app.asar/src/browser/atom-application.js:925:24
    at Function.wrappedCallback (/Applications/Atom Beta.app/Contents/Resources/atom.asar/browser/api/lib/dialog.js:82:16)
28/11/15 10:36:51,594	Atom[1076]	App load time: 353ms
```

If I want to close the empty pane I have to select VIEW -> PANES -> CLOSE PANE from the dropdown menu.

May I ask you if this a bug or the normal behaviour of Atom?

If this is the correct behaviour in this case, may I say that IMHO it would be more intuitive to expect that when you close the last tab in a pane, that pane would disappear.

Thank you for reading my message and best regards

**Comment by izuzak** [comment]
Do you have this option enabled or disabled in your settings?

<img width="379" alt="screen shot 2015-11-28 at 11 02 43" src="https://cloud.githubusercontent.com/assets/38924/11451268/a5212334-95bf-11e5-9b99-13319a4dcbfb.png">

If it's not enabled, can you try enabling it and see if that helps?

**Comment by fmaida** [comment]
No, I had that option disable (I'm an idiot...)

**Comment by izuzak** [comment]
Thanks for following up. Also, I recommend you follow this guide when reporting problems:

https://github.com/atom/atom/blob/master/CONTRIBUTING.md#reporting-bugs

That guide would have taken you to the debugging guide here:

https://atom.io/docs/latest/hacking-atom-debugging

And there's a section in that debugging guide which tells you to check the settings, which would have helped you:

https://atom.io/docs/latest/hacking-atom-debugging#check-atom-and-package-settings
