### ISSUE TITLE
Capturing errors always runs `apm ls --json --no-color` and renders atom unusable for an amount of time

### ISSUE THREAD

**Issue by despairblue** [atom/atom#9856]
Everytime an error dialog is shown:

![screen shot 2015-11-28 at 13 54 04](https://cloud.githubusercontent.com/assets/927609/11451960/91e00a5c-95d7-11e5-95be-4077a3bfe44a.png)

Atom runs `apm ls --json --no-color` producing this profile

![screen shot 2015-11-28 at 13 55 12](https://cloud.githubusercontent.com/assets/927609/11451963/b3b1f4e2-95d7-11e5-9129-cead20ff82e2.png)

![screen shot 2015-11-28 at 13 58 07](https://cloud.githubusercontent.com/assets/927609/11451975/20a8ce54-95d8-11e5-8934-e17708265a2d.png)

It renders atom unusable for about a minute or so (using 100% cpu for handling `apm ls --json --no-color`'s output, which is only **10mb**)

Also clicking the reporting button has no effect until atom finishes this process.

It could be one reason for https://github.com/atom/atom/issues/3426

I tried to find the code that runs `apm ls --json --no-color`, but unsuccessful.

## Versions

* **Atom:**       1.3.0-beta6
* **Atom-Shell:** 
* **OS:**         Mac OS X 10.10.5
* **Misc**
    * apm  1.1.1
    * npm  2.13.3
    * node 0.10.40
    * python 2.7.10
    * git 2.5.1

**Comment by despairblue** [comment]
I could also upload the whole cpuprofile, just tell me where.

**Comment by 50Wliu** [comment]
Hey @despairblue, could you please move this over to [atom/notifications](https://github.com/atom/notifications)?  That's probably also where the `apm` command is being called.  Thanks!
