### ISSUE TITLE
Custom test runner using Mocha and Coverage

### ISSUE THREAD

**Issue by mrodalgaard** [atom/atom#9859]
I'm trying to use [Mocha](mochajs.org) for Atom package specs and have hit several obstacles in my way.

The ultimate goal of this is to achieve test coverage for package specs using [coffee-coverage](https://github.com/benbria/coffee-coverage). And I just prefer Mocha over Jasmine in general.

Using custom test runner (#8968) with the following `atomTestRunner` file:

https://gist.github.com/mrodalgaard/8961e8760e6c408350f9
- [x] **Spec window does not open in devMode**
  Opened spec window when using `Window:Run Package Specs` starts in non-development mode even though Atom is in development mode. So I have to force it into devMode by redirecting the url - very ugly. Setting devMode on `applicationDelegate` did nothing and setting devMode on the atom global seems to be too late for package load paths (`packages.packageDirPaths`).
  --- Fixed in #9476 ---
- [x] **Package using activationCommands does not activate**
  Currently I'm just testing this on the [default package](https://github.com/atom/package-generator) modified for Mocha and Chai expect. The problem is that the `activatePackage` promise never resolves even though the package seems to load. This works with Jasmine without the custom test runner. And when I remove `activationCommands` from package.json it resolves and Mocha runs the tests successfully.
  --- Fixed by not returning a promise in Mocha's beforeEach ---

``` coffee
beforeEach ->
  workspaceElement = atom.views.getView(atom.workspace)
  # With activationCommands this never resolves
  activationPromise = atom.packages.activatePackage('demo-package')
```
- [x] **Content Security Policy on 'unsafe-eval'**
  [coffee-coverage](https://github.com/benbria/coffee-coverage) ultimately fails on eval because the spec window is opened with restrictive Content-Security-Policy. [electron issue](https://github.com/atom/electron/issues/3430) and [atom PR](https://github.com/atom/atom/pull/1702) mentions this, but I could not see how `allowUnsafeEval` could be set by the developer.
  --- Fixed by using [loophole package](https://www.npmjs.com/package/loophole) even though is feels like a hack ---
- [ ] **Coverage runs, but reports 0%**
  Files that are wrapped by coverage (Esprima and Escodegen) are apparently not the ones being run by Atom or a child process is spawned before tests run like hinted to [here](https://github.com/benbria/coffee-coverage/issues/60).

Using Mac OSX 10.11.1, Atom 1.2.4 and Atom 1.3.0-beta6.

Apologize for the long post, but I felt it all belonged here to get the full picture.

**Comment by nathansobo** [comment]
> The problem is that the `activatePackage` promise never resolves even though the package seems to load.

You'll have to dispatch an activation command. I agree this isn't ideal, and I'd like to have a better API for unconditionally activating a package in tests. There *is* a private `Package.prototype.activateNow` method you could call, but it's not part of the officially supported API and is subject to change in the future.

> Files that are wrapped by coverage (Esprima and Escodegen) are apparently not the ones being run by Atom or a child process is spawned before tests run

We don't spawn any special subprocesses once your test window has booted and your test runner initialization code runs. We do have a [caching system](https://github.com/atom/atom/blob/master/src/compile-cache.js) in place that circumvents CoffeeScript compilation when scripts haven't changed. Could that be interferring?

**Comment by mrodalgaard** [comment]
Thank you for the feedback @nathansobo.

> You'll have to dispatch an activation command. I agree this isn't ideal, and I'd like to have a better API for unconditionally activating a package in tests. There is a private Package.prototype.activateNow method you could call, but it's not part of the officially supported API and is subject to change in the future.

As I mentioned I'm using the [default package](https://github.com/atom/package-generator) which uses `atom.commands.dispatch workspaceElement, 'demo-package:toggle'` later in test to activate. It eventually turns out that Mocha's `beforeEach` function waits for the promise to resolve whereas Jasmine just moves forward, so all I had to do is return something else other than a promise.

```
  beforeEach ->
    workspaceElement = atom.views.getView(atom.workspace)
    attachToDOM(workspaceElement)
    activationPromise = atom.packages.activatePackage('demo-package')
    return true
```

I also had to implement the attachToDOM function similar to what you guys do in `spec-helper.coffee`.

```
  attachToDOM = (element) ->
    unless specContent = document.querySelector('#spec-content')
      specContent = document.createElement 'div'
      specContent.id = 'spec-content'
      document.body.appendChild(specContent)
    specContent.appendChild(element) unless specContent.contains(element)
```

> We don't spawn any special subprocesses once your test window has booted and your test runner initialization code runs. We do have a caching system in place that circumvents CoffeeScript compilation when scripts haven't changed. Could that be interferring?

This might be a problem if the coffeescript that runs is actually the cached code and not the coverage wrapped. On the other hand the paths when breaking in code or looking at the development 'Sources' tab seems correct (might be because of javascript/coffeescript map files).

This might also explain why I have to sometimes refresh a few times before the spec changes take effect.

Any way to disable the caching when testing? Or circumvent it temporary to see if this is causing the problem? Is this set on Electron or something specific to Atom?

**Comment by jccguimaraes** [comment]
any luck on the coverage?

have been trying also Mocha+Istanbul. Have managed to make the report work but can't add the actual coverage.

Please check my gist [here](https://gist.github.com/jccguimaraes/2e08be6f549448d9361c)!

**Comment by mrodalgaard** [comment]
@jccguimaraes, no, sorry. Seems like I keep getting the wrong files instrumented, so reports are always *0 coverage*. Cannot see how your method targets the Atom cached files. You are targeting spec files in `test/models` and source files in `lib/models`, both in JavaScript and not CoffeeScript?
