### ISSUE TITLE
highlight of .h file

### ISSUE THREAD

**Issue by zhanglongqi** [atom/atom#9862]
The highlight of `#ifdef` and `#endif` at line 9 and line 21
![snip20151129_9](https://cloud.githubusercontent.com/assets/956693/11456466/d7c11ff0-96c4-11e5-9a32-be999cccc301.png)
![snip20151129_10](https://cloud.githubusercontent.com/assets/956693/11456476/17df6baa-96c5-11e5-8d8c-8102eac1bdb5.png)

```c
/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class JNIFoo */

#ifndef _Included_JNIFoo
#define _Included_JNIFoo
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     JNIFoo
 * Method:    nativeFoo
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_JNIFoo_nativeFoo
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
```

**Comment by mnquintana** [comment]
Would you mind reopening this on https://github.com/atom/language-c? Thanks!

**Comment by zhanglongqi** [comment]
OK
