### ISSUE TITLE
Long minified files make it crash!

### ISSUE THREAD

**Issue by abelncm** [atom/atom#9865]
Because bootstrap.min.css is long horizontaly, it makes Atom crash everytime.
When I reopen Atom, it crashes again because it opens in that file.

**Comment by abelncm** [comment]
Should have a better way to handle crashes, it's really terrible at it!

**Comment by mnquintana** [comment]
This is a duplicate of https://github.com/atom/atom/issues/979 – feel free to subscribe there for updates.
