### ISSUE TITLE
[find-and-replace] The option "Open project find results in right pane" is not always respected

### ISSUE THREAD

**Issue by fabiospampinato** [atom/atom#9866]
If I perform a project-level find the results pane gets opened at the right side, since I've set the "Open project find results in right pane" option "on" in the settings. No matter if I have some other tabs open or not. So far so good.

The problem comes if I have something at the left and the results pane at the right: if I close everything at the left, now that there's nothing more, the results pane expands to fit the whole space.

I believe this shouldn't happen since when there are no tabs the results pane is still opened at the right, leaving nothing at its left.

I'm using Atom Beta v1.3.0-beta0

**Comment by thedaniel** [comment]
This is a side effect of how pane splits work by default. I suppose we could special case not closing a pane after the last tab is closed if this setting is on and the FNR tab is visible, but I'm not sure it's worth adding the complexity, especially since that would involve changing core behavior based on a package setting.

**Comment by fabiospampinato** [comment]
Understandable, but I think that consistency is at least as important.

Right now I can't think of any plain and simple solution to fix it, but maybe we could add an API that a tab can call to set its preferred pin direction, so that when comes the time to close a pane we can use these informations to properly adjust the splits. This wouldn't be find-and-replace-specific and, in the case these kind of packages needed some extra code in order to provide the "Open in [direction] pane" functionality, we will make it already coded for them.
