### ISSUE TITLE
Changing CSS of an HTML file with the Markdown Preview Open changes IDE CSS

### ISSUE THREAD

**Issue by bahiafayez** [atom/atom#9868]
I created a new HTML file, and started adding styles to it and all. As soon as I open the markdown preview (Shift + Cmd + P and choose the markdown preview toggle), the Navigation CSS changes as well!

I attached a screenshot with the issue, you'll see that the HTML file and the Markdown preview are both open. I was setting the span style to have a green border, you'll see that the navigation on the left hand side also has a green border.

I'm running **Atom 1.2.4** on **OSX El Capitan version 10.11.1** 

<img width="852" alt="screen shot 2015-11-30 at 11 01 23" src="https://cloud.githubusercontent.com/assets/1146241/11467695/7c1abac4-9752-11e5-84c4-ef8405d1fd0b.png">

**Comment by thedaniel** [comment]
Can you reproduce this after starting Atom in safe mode?

**Comment by bahiafayez** [comment]
Ok so I just started atom with 

     atom --safe
and I still got the same behaviour.
