### ISSUE TITLE
I'm on 1.2.4 but Release Notes page invites me to update to 1.1.0

### ISSUE THREAD

**Issue by flaviolaino** [atom/atom#9869]
Windows 8.1

![image](https://cloud.githubusercontent.com/assets/10008037/11467989/75b9fe02-974c-11e5-8b59-c9e0d195166c.png)

**Comment by arthurwhite** [comment]
Problem and solution are known: #3757.

> The plan is to remove the release notes package and have all the update logic in the about page similar to chrome. See #9164 for more details. — @benogle

**Comment by rsvargas** [comment]
It's still a bug tough.
