### ISSUE TITLE
Use atom-launcher to fix #4893

### ISSUE THREAD

**Issue by jhasse** [atom/atom#9870]
I can't comment on #4893, but I actually want to post a useful workaround: http://discuss.atom.io/t/windows-explorer-file-associations-for-atom/21656

Can this be integrated into atom to fix #4893?

**Comment by thedaniel** [comment]
@raelyard any comment on this?

**Comment by raelyard** [comment]
I was hoping the registry edit shown would work with the .cmd file, but it doesn't seem to.  Noticing VS Code is registering itself up to be shown as an option for mutliple files types.  Might be ideal to do that - looks like a lot of registry manipulation to make that happen.  The launcher cited here is probably a quicker fix.  It's a C# console application, which means there's a dependency on .NET, which is probably not ideal, but Squirrel also means a dependency on .NET for the installer, so probably not a huge deal.

**Comment by Xcodo** [comment]
Currently the project I wrote is targeted at .NET 2.0 (on the lowest common denominator principle), but there isn't compatibility for that bundled with Windows 8 onwards. Squirrel looks like it's targeted at .NET 4.5 (through that isn't bundled with Windows 7), so I guess changing atom-launcher to that might make sense.

**Comment by damieng** [comment]
#4893 was fixed without a need for an intermediate application, closing this issue.
