### ISSUE TITLE
Default font size reset / deleted after command window:reset-font-size

### ISSUE THREAD

**Issue by DerToti** [atom/atom#9873]
Hello everyone im not really sure if this is a bug or not.

In my config.cson i have fontSize setup to 11 and on the settings section as well on 11.

The problem now is when im zooming in in the editor, and press cmd-0 to call the reset-font-size command i would suggest to have my font size reseted to 11 again (my default font size) but instead it is reseted to 14 i think and on the config.cson my fontSize 11 is gone as well on the settings section.

T think this was working before (don't know when it broke).

**Comment by jirsbek** [comment]
Exactly same problem here. Sometimes I accidentally hit wrong key combination on num keyboard and font get bigger. I'm used to hitting reset font size when that happens but since 1.2.3 or 1.2.4 it just deletes font size setup.

**Comment by mnquintana** [comment]
Thanks for the report! I can reproduce this on 1.2.4 - this is definitely a regression.

**Comment by brentshermana** [comment]
The default font size for atom is size 14, which is defined in src/config-schema.coffee. I would expect a command called 'Reset font size'  to switch the font size to a default value, so I don't consider this a bug.

Perhaps what you have in mind is a command which undoes the last font change? That sounds a bit nichè, but it could be implemented pretty easily.

**Comment by thomasjo** [comment]
@brentshermana It's supposed to reset to the user's default font size, i.e. what was originally specified in their `config.cson` file. This was fixed at some point, but then later regressed. This regression is still alive, but should be squashed.

@atom/feedback Anyone have any immediate thoughts on what might have caused this regression? Perhaps the config schema in package.json changes caused this somehow? We should definitely look into this, starting by implementing a failing spec to prevent further regressions in the future.

**Comment by iolsen** [comment]
cc @damieng

**Comment by lee-dohm** [comment]
https://github.com/atom/atom/pull/6539 is the PR where @mnquintana made the change to `reset-font-size` so that it restored the font size at window startup.

**Comment by damieng** [comment]
I would imagine reset font size should reset the font size back to what it was before it was increased/decreased using the appropriate zoom functions.  

I'm not quite sure what that PR was aiming to achieve but the net effect seems to be it just clears the setting in your config for you.

**Comment by thomasjo** [comment]
If you look at the commits, the PR watched for changes to font size in user config, and stored the original value prior. Then upon invoking reset, it sets font size to the original value instead of clearing the value. 

This used to work, but broke at some point. It's unfortunate that the spec from the PR did not catch the regression.

**Comment by mobusby** [comment]
Sure would be nice if the user could set their own default font size, then zoom in/out based upon that *user specified* default font size.  Sure it's a bit of a shift in thinking, user default instead of program default, but the upshot is greater usability across widely varying displays and preferences.

**Comment by josephessin** [comment]
Came here because when I press Cmd+0 to reset font size, I naturally EXPECT it to reset to my own specified font size in the editor settings, NOT some predetermined default. As someone who's written a word processor and done a lot of other writing, I, like anyone else, **would expect the zooming in and out to be relative to the default font size I specified**.

Can we get a fix on this? I'm new to Atom and I'm getting the packages setup...I'm not familiar with the codebase at all.

**Comment by josephessin** [comment]
Okay, I think I may have found the culprit in [atom/src/workspace.js](https://github.com/atom/atom/blob/5e079866991689eb0b576a94cd654e78fb178465/src/workspace.js):

 ```
 // Increase the editor font size by 1px.
  increaseFontSize () {
    this.config.set('editor.fontSize', this.config.get('editor.fontSize') + 1)
  }

  // Decrease the editor font size by 1px.
  decreaseFontSize () {
    const fontSize = this.config.get('editor.fontSize')
    if (fontSize > 1) {
      this.config.set('editor.fontSize', fontSize - 1)
    }
  }

  // Restore to the window's original editor font size.
  resetFontSize () {
    if (this.originalFontSize) {
      this.config.set('editor.fontSize', this.originalFontSize)
    }
  }
```

I'm not sure what it's doing exactly because earlier in that file we see that `this.originalFontSize = null`

**Comment by josephessin** [comment]
Update: I think I may have figured it out. In the same workspace.js file we see this right after resetFontSize():

```  subscribeToFontSize () {
    return this.config.onDidChange('editor.fontSize', ({oldValue}) => {
      if (this.originalFontSize == null) {
        this.originalFontSize = oldValue
      }
    })
  }
```

I suspect that's what happening is that this.originalFontSize is only ever be updating when atom first opens and notifies it, because of the check for `this.originalFontSize == null`

If we remove that, it should keep track of the original font size whenever the user updates it, right?

**Comment by chibicode** [comment]
@josephessin as a short term workaround, this is what I did: hardcoding.

In `~/.atom/init.coffee`:

```coffee
atom.commands.add 'atom-text-editor',
  'user:set-font-size-to-15': (event) ->
    atom.config.set("editor.fontSize", 15)
```

In `~/.atom/keymap.cson`:

```cson
'atom-text-editor':
  'cmd-0': 'user:set-font-size-to-15'
```

**Comment by josephessin** [comment]
@chibicode I'll give that shot. I poked around the codebase some more and realized that the text view component relies on the global setting of font size, NOT it's own display version, and we would have to refactor it to rely on it's own internal version that is adjusted for zooming based off the global setting. I didn't want to attempt that without familiarizing myself further with the codebase, for fear of breaking all of it.

**Comment by swirlsky** [comment]
Using v1.22.1, the issue still exists.

**Comment by dbugdan** [comment]
For those of you using @chibicode's workaround, I had to change `'atom-text-editor'` to `'body'`  in `~/.atom/keymap.cson` to get it working on the latest version (1.23.3). 

```cson
'body':
  'cmd-0': 'user:set-font-size-to-15'
```

**Comment by ricklecoat** [comment]
For the record: I'm still seeing this in Atom 1.34.0 (Mac), but Caleb Meyer over on Slack reports that it Cmd-0 performs as expected  on Windows (ie. resets font-size to the user-defined non-out-of-the-box-default). So may be just an issue on the Mac side?

**Comment by nathansobo** [comment]
Let me try and clarify what people's expectation is here. Currently, resetting the font size is about restoring the font size that was assigned when the window was initially opened.

It sounds like people are expecting the font size to be reset to whatever value they explicitly assigned in the settings, basically wiping out any adjustments made via the the `window:increase-font-size` or `window:decrease-font-size` commands. Is this correct?

**Comment by bcorcoran** [comment]
Yes. Just like when you set a font size in your browser... CMD/CTRL+0 resets it to that value.

From a UX standpoint, why would you want it to do anything else? If we wanted the default value, we'd remove the explicit value from the config...

**Comment by vinkla** [comment]
> It sounds like people are expecting the font size to be reset to whatever value they explicitly assigned in the settings, basically wiping out any adjustments made via the the `window:increase-font-size` or `window:decrease-font-size` commands. Is this correct?

Yes, I would expect setting the font size from the editor settings should be the true/default font size.

**Comment by blizzardengle** [comment]
I'm curious how this is still open? Can someone provide an update or at the vary least make a new function like `window:font-to-default` or `window:font-to-users-default`. This make teaching class in Atom via video calls rather annoying, especially with students who are new to Atom to begin with.

**Comment by UziTech** [comment]
So we have a `fontSize` setting that is updated when calling `window:increase-font-size` and `window:decrease-font-size` but we need a `defaultFontSize` setting that can be set in the settings and is what is used to reset `fontSize` when `window:reset-font-size` is called.

Currently `defaultFontSize` is just whatever the `fontSize` was set to when the window opened.
