### ISSUE TITLE
smb MyCloud files not opened correctly under 64-bit Ubuntu 15.10

### ISSUE THREAD

**Issue by RolandHughes** [atom/atom#9874]
This appears to be a Linux specific bug. Test system is quad-core I7 with 16Gig of RAM running Ubuntu 15.10 with all updates applied. Atom is installed from the wily main PPA so it stays relatively current automatically. Share device is a Western Digital MyCloud 4TB device. Same machine booting 64-bit Windows 7 Pro with Atom has no problem opening text files on the drive. On Ubuntu I can double click a text file and gedit opens it fine. If I right click on to-do.txt and select "open with atom" atom comes up, it displays the file name on top, but an empty tab. Editing files with all other text editors works fine. It appears Atom is doing something incorrectly for smb mounted shares under Ubuntu 15.10.

**Comment by thedaniel** [comment]
Thanks for the report - there are some related issues in #9824 and #1766
