### ISSUE TITLE
Moving a folder in the Tree View does not close the corresponding file buffers.

### ISSUE THREAD

**Issue by lczech** [atom/atom#9875]
When dragging a file in the Tree View into a different folder, any buffers of this file are closed. I guess, this is desired behaviour. (Alternatively, the buffer could stay open and internally change the file it is referring to, but this is another topic.)

However, the behaviour is different when instead of a file a whole folder is moved (via drag and drop) in the Tree View: Buffers of files in the folder stay open, and upon closing them manually, a dialogue "file.xyz has changes, do you want to save them?" is triggered. This is certainly not good behaviour. The buffers should be closed instead.

Furthermore, if the file is not yet added to git, it is marked green in the Tree View, along with all higher level folders. If now a folder with such a new file is moved, the green marking does not update properly for the higher level folders.

Using:
atom 1.2.4
tree-view 0.195.0
ubuntu 14.04

**Comment by lczech** [comment]
Just found a new bug: Something similar happens when renaming a folder in the Tree View while files of that folder are opened: The files stay open, but are marked as unsaved. When saving them, the old folder name is created again, with the file in it. So then there are two copies of that file, one in the renamed folder and one in the folder with the old name that was just created again.

**Comment by ungb** [comment]
I am able to repro this when I am moving folders, when I save the files that are open it recreates the old folder in old location.

This is kind of related to https://github.com/atom/tree-view/issues/948
