### ISSUE TITLE
Atom is crashing

### ISSUE THREAD

**Issue by niltz** [atom/atom#9880]
Today Atom has been crashing a lot for me. Here is a crashlog:
[Atom Helper_2015-11-30-164637_jsawatzky.crash](https://github.com/atom/atom/files/47848/Atom.Helper_2015-11-30-164637_jsawatzky.txt)

I disabled the git-dff and open-in-guthub packages hoping it would solve it, but it didn't.

**Comment by Announcement** [comment]
is node/atom/etc. the latest version?
try enabling all of the core plugins and none of the other ones.
is this the only app this is happening with?

because from what you've shown it actually reminds me of what happens when your cpu experiences a damaging power surge or whatever; but hopefully its something we can fix with code or configuration.

**Comment by niltz** [comment]
@Announcement, I have Atom version 1.2.4 (which is the current latest version). I'm not sure how to check which version of node it is using.

I've noticed that it crashes only on certain files, and only when I modify them. If I git reset the file and open it in atom it doesn't crash. But once I modify it and save it, it crashes. If I try to reopen it, it crashes. I can reproduce it consistently with the same files, but it doesn't happen with all files. This is why I disabled the git-diff plugin (it seemed related).

I've disabled on community packages and enabled all core ones and it still crashes.

This seems to have started to happen after I installed https://support.apple.com/kb/DL1803?locale=en_US

**Comment by thedaniel** [comment]
@zcbenz is there anything that indicates any known electron bugs in this crash report?

**Comment by niltz** [comment]
Any idea on what might be causing this? I've had to switch to sublime text for now. :cry:

**Comment by zcbenz** [comment]
It looks like a bug of libgit2:

```
0   libsystem_kernel.dylib        	0x00007fff94240286 __pthread_kill + 10
1   libsystem_c.dylib             	0x00007fff98a28a53 __abort + 145
2   libsystem_c.dylib             	0x00007fff98a29331 __stack_chk_fail + 197
3   git.node                      	0x000000010fadd40e diff_context_line__pattern_match + 249
4   git.node                      	0x000000010fadd2e2 diff_context_find + 91
5   git.node                      	0x000000010fb37152 get_func_line + 152
6   git.node                      	0x000000010fb36df6 xdl_emit_diff + 696
7   git.node                      	0x000000010fb36980 xdl_diff + 385
8   git.node                      	0x000000010fae3e75 git_xdiff + 290
9   git.node                      	0x000000010faded07 diff_patch_generate + 406
10  git.node                      	0x000000010fadf5f7 git_patch_from_diff + 493
11  git.node                      	0x000000010fabf0e9 Repository::GetDiffStats(Nan::FunctionCallbackInfo<v8::Value> const&) + 607
12  git.node                      	0x000000010fac16f1 Nan::imp::FunctionCallbackWrapper(v8::FunctionCallbackInfo<v8::Value> const&) + 131
13  libnode.dylib                 	0x0000000105e4975f v8::internal::FunctionCallbackArguments::Call(void (*)(v8::FunctionCallbackInfo<v8::Value> const&)) + 159
14  libnode.dylib                 	0x0000000105e727b9 v8::internal::Builtins::InvokeApiFunction(v8::internal::Handle<v8::internal::JSFunction>, v8::internal::Handle<v8::internal::Object>, int, v8::internal::Handle<v8::internal::Object>*) + 1561
```

**Comment by benogle** [comment]
Wonder if related to #9339

**Comment by ondine** [comment]
![screen shot 2015-12-14 at 11 42 40 am](https://cloud.githubusercontent.com/assets/3281541/11791901/436e0a80-a258-11e5-9826-e66cd776fafc.png)

Crashing in Yosemite 10.10.5, Atom v 1.3.1. Happens whenever it is re-opened. The issue began with text not displaying correctly (partial text missing) within a .md file, then crashed entirely. Upon restart of the Atom, shows error displayed above.

**Comment by viatsko** [comment]
Should be fixed by this PR, testing on Windows https://github.com/atom/git-utils/pull/61

**Comment by joshaber** [comment]
The git-utils PR was merged and git-utils was bumped in https://github.com/atom/atom/pull/10247.
