### ISSUE TITLE
Syntax highlighting on array stops after 47 items on single line

### ISSUE THREAD

**Issue by nicekiwi** [atom/atom#9882]
I have an array with many numbers on a single line, after 47 numbers the syntax highlighting stops.

![47ids](https://cloud.githubusercontent.com/assets/738975/11488803/25af123e-982e-11e5-9cd7-0d629eb07338.PNG) 

After the end of the array, normal syntax colouring continues as expected. 

Atom v1.2.4 - Windows 7 x64

Theme is `Monokai For One Dark`, but the issue appears on the default Atom themes as well.

**Comment by 50Wliu** [comment]
Atom currently does not syntax highlight long lines for performance reasons - please see #1667 for more details.
