### ISSUE TITLE
Files in `.gitignore` are not in tree view

### ISSUE THREAD

**Issue by qanx** [atom/atom#9883]
Previously these files were just greyed out - this was actually very helpful. Typically the only reason I have a file in `.gitignore` is when I have a file that has things like keys that I don't want to push to the repo but that I still need to touch from time to time. Not being able to see these files _at all_ is hugely inconvenient and was a huge surprise :(

**Comment by 50Wliu** [comment]
You probably pressed `i` by accident while the Tree View had focus.  Try focusing the Tree View again and pressing `i` :wink:.

**Comment by qanx** [comment]
Ack I didn't even notice there were keyboard shortcuts to use with Tree View. Sneaky! And thank you! :D
