### ISSUE TITLE
Want to add text 2/3 sublime, the right side of the preview of the scroll bar

### ISSUE THREAD

**Issue by 120011676** [atom/atom#9884]
Want to add text 2/3 sublime, the right side of the preview of the scroll bar

**Comment by amytruong** [comment]
Are you wondering if there's a way to preview the whole source code? If so, there certainly is. It's a package that you can install. :point_down: 
https://atom.io/packages/minimap

If not, can you please clarify a bit? Thank you!

**Comment by 120011676** [comment]
@amytruong Very good，Thank you!

**Comment by amytruong** [comment]
No problem! Glad I could help! :smile:

**Comment by 120011676** [comment]
@amytruong You that should be the night, still do not sleep?
