### ISSUE TITLE
I hope to release the green version (not installation，unzip).

### ISSUE THREAD

**Issue by 120011676** [atom/atom#9886]
I hope to release the green version (not installation，unzip).

**Comment by 50Wliu** [comment]
I believe this was opened by accident - if I'm misunderstanding something, please comment here @120011676!

**Comment by 120011676** [comment]
@50Wliu 
 zip Binary linux
 not .deb， ......

I'm sorry，
English is not good。

**Comment by 50Wliu** [comment]
@120011676 Ok, then please see #7102 for updates.

**Comment by 120011676** [comment]
@50Wliu Oh,Ok
