### ISSUE TITLE
'Window' menu doesn't list any windows

### ISSUE THREAD

**Issue by danfooo** [atom/atom#9888]
After opening a file or a folder in atom there are never any entries in the "Window" menu. Opening more windows doesn't add any entries either.

<img width="209" alt="screen shot 2015-12-01 at 10 41 24" src="https://cloud.githubusercontent.com/assets/131394/11497268/22a995b6-9818-11e5-9d71-6368bad7be75.png">

I see this in 1.2.4 on Mac OS 10.11.1

**Comment by 50Wliu** [comment]
This has already been fixed in the 1.3.0 betas.

**Comment by danfooo** [comment]
That's great, thanks!
