### ISSUE TITLE
Update Impossible

### ISSUE THREAD

**Issue by MrMic** [atom/atom#9889]
When i am on the Update tab and click "Check for Updates", i got this message:
"Fetching outdated packages and themes failed.
Request for packege information failed: Application error"

Thanks for fixing it.
Rgds,

**Comment by sammosam** [comment]
i am facing same issue for quite a few days now. is there any fix yet?

**Comment by giano** [comment]
Confirm: same issue.

**Comment by thedaniel** [comment]
We had some uptime issues with the API - are you still seeing this issue?

**Comment by MrMic** [comment]
No, it seems OK today.

**Comment by thedaniel** [comment]
OK, I'm going to close this issue then, assuming it was related to the API flakiness.

**Comment by darkred** [comment]
Most of the times, since yesterday I get the error `"Fetching outdated packages and themes failed`.
_Using Atom 1.6.2 in win10 x64._

Clicking show output shows:
![2016-04-13_212329](https://cloud.githubusercontent.com/assets/723651/14504559/02021d28-01be-11e6-8c44-dd63431d358b.png)
