### ISSUE TITLE
Improve the dock right-click menu on Mac

### ISSUE THREAD

**Issue by a7madgamal** [atom/atom#9890]
I use Atom on Mac 90% of my time and I really think the right click menu can be improved to make my life much easier and make the world a better place in general :D 
So this is how the current right click menu looks like when I have many windows (aka projects) open at the same time:
![atom right click](https://cloud.githubusercontent.com/assets/939602/11501061/9854cccc-9831-11e5-8082-e168fc120a48.png)

Meanwhile on Sourcetree which is another favorite I use all the day too : 
![source tree menu](https://cloud.githubusercontent.com/assets/939602/11501062/98556948-9831-11e5-992f-d39a03823737.png)

and here is why I like the Sourcetree version!

1- it's WAY faster to check or switch to other open projects (including minimized windows that cmd + ` ignore)
2- the top part of the menu is even more interesting because I can easily open recently closed projects so it's much easier and safe to close projects I'm not working on right now but I may need to work on soon
3- it feels more native and Mac-ish :D

Atom 1.2.4 on Mac 10.11.1

**Comment by 50Wliu** [comment]
I believe this is being worked on by @DouweM in multiple PRs right now - see #9609, #9606, and more.

Also see #3935 for the original issue.  Hope this helps!
