### ISSUE TITLE
Certain panels in Atom will not render completely

### ISSUE THREAD

**Issue by sqmk** [atom/atom#9892]
I've noticed various panels in Atom are not being rendered completely. Adjusting the editor size will change the results of the partial rendering. Example of rendering differences when changing width of the entire window:

<img width="1064" alt="screen shot 2015-12-01 at 11 14 39 am" src="https://cloud.githubusercontent.com/assets/279474/11508252/590a98d0-981d-11e5-8c21-f506763e7372.png">
<img width="1157" alt="screen shot 2015-12-01 at 11 14 44 am" src="https://cloud.githubusercontent.com/assets/279474/11508265/71742116-981d-11e5-899d-5dd160d1c170.png">
<img width="1280" alt="screen shot 2015-12-01 at 11 14 50 am" src="https://cloud.githubusercontent.com/assets/279474/11508270/773ebc3c-981d-11e5-8c2f-931bdba37012.png">

So far, I've noticed this behavior on the following:
- Atom > Preferences > Installed Packages
- Markdown preview

Tested on v1.2.4 and v.1.3.0-beta6, community extensions disabled. System info below:

<img width="586" alt="screen shot 2015-12-01 at 11 09 41 am" src="https://cloud.githubusercontent.com/assets/279474/11508240/3c8f363e-981d-11e5-95f2-6bf959e758d5.png">

**Comment by 50Wliu** [comment]
Refs atom/one-dark-ui#109.

**Comment by Ben3eeE** [comment]
This has been fixed by https://github.com/atom/one-dark-ui/pull/112
