### ISSUE TITLE
Atom 1.2.4 RPM binary works under 64-bit Mageia 5

### ISSUE THREAD

**Issue by fusion809** [atom/atom#9893]
Hi,

This isn't so much a problem, but as the current [linux.md](https://github.com/atom/atom/blob/master/docs/build-instructions/linux.md) and [README.md](https://github.com/atom/atom/blob/master/README.md) files do not contain any instructions relating to Mageia I thought I should mention this. See what I did was I ran:

    urpmi https://github.com/atom/atom/releases/download/v1.2.4/atom.x86_64.rpm

as root. The first time I ran this I was informed that `/usr/bin/apm` from Atom conflicted with `/usr/bin/apm` from the [apmd package](http://rpmfind.net/linux/RPM/mageia/5/x86_64/media/core/release/apmd-3.2.2-32.mga5.x86_64.html). So I uninstalled apmd and re-ran this command and I managed to successfully install Atom 1.2.4 on Mageia 5. 

Thanks for your time,
Brenton

**Comment by 50Wliu** [comment]
I believe there was another issue regarding the conflict between `apm` and `apmd` which basically ended with the conclusion that `apmd` was horribly outdated and unsupported, so the best solution would be to uninstall it.

That `linux.md` file is only for building Atom whereas you seem to be installing it.
