### ISSUE TITLE
Window menu doesn't list windows on OS X 10.11

### ISSUE THREAD

**Issue by danielbayley** [atom/atom#9895]
I have 4 open but…
![atom](https://cloud.githubusercontent.com/assets/7797479/11511465/247c1a50-9861-11e5-8919-8ed1a26b1ea0.png)

---

Mac OS X 10.11
Atom 1.2.4

**Comment by eboracus** [comment]
Tried on the same setup and confirm I am also seeing (or _not_ seeing) this too.

**Comment by 50Wliu** [comment]
This has already been fixed in the 1.3.0 betas.

**Comment by ttrahan** [comment]
As a workaround, deleting your files in ~/.atom/storage appears to resolve the issue in v1.3.2
