### ISSUE TITLE
Search all does not redo search after unchecking "Exclude VCS Ignored Paths"

### ISSUE THREAD

**Issue by smith-kyle** [atom/atom#9896]
**Repro Steps**
1. Ensure that *Exclude VCS Ignored Paths* is enabled
2. Search all for a specific string
3. Disable *Exclude VCS Ignored Paths*
4. Make another search with the same string

**Expected Behavior**: A new search should be made and I should see the new results
**Actual Behavior**: The search is not done and the results stay the same

**Comment by thedaniel** [comment]
Thanks for the bug report & detailed repro steps. I'll move this issue to the find-and-replace repo.

**Comment by thedaniel** [comment]
This issue was moved to atom/find-and-replace#609
