### ISSUE TITLE
Packages results order

### ISSUE THREAD

**Issue by montogeek** [atom/atom#9897]
Hi!

 What is the criteria to list the packages search results?

**Comment by thedaniel** [comment]
It's sorted by relevance to the search query. The packages are indexed in elasticsearch on the name, readme, description, keywords, etc.

**Comment by evotopid** [comment]
There is an issue with the ordering though (and as I don't know if there is another issue for this I'm adding it here): The example is search for "linter". You will get many results of packages including linter in their name before actually finding the package only called linter. I think if there is an exact match for a packages name it should be the first one in the result list regardless of the "relevancy".

**Comment by Julix91** [comment]
Much agreed. As a newb I really don't want to be looking through a bunch of things and guessing based on the number of users that it's the one I'm looking for... - also why no date? version numbers don't mean much between different packages, right?

**Comment by Ben3eeE** [comment]
The criteria changed with https://github.com/atom/settings-view/pull/761. It is now (Or when an Atom version with this PR gets released) ordered by download count with a possible exact match always on the top.
