### ISSUE TITLE
atom.project.addPath : Relative paths add super folder instead.

### ISSUE THREAD

**Issue by james-y** [atom/atom#9899]
### Reproduce:

Add a directory to the path using a relative path, e.g.:

```
atom.project.addPath("DirectoryName")
atom.project.addPath("./DirectoryName")
```

When using the relative paths, the final result in the project explorer window is a directory with a name consisting only of a period (e.g: '.') and the contents of the specified directory listed.
![screenshot after adding relative path - 1 of 2](https://cloud.githubusercontent.com/assets/8364502/11519026/74aac56e-984b-11e5-9182-98afd40e24fd.png)
Closing and re-opening (Tipping) the containing directory '.', results in all files/directories that are siblings to 'DirectoryName' being added to the project explorer window.  I suspect the super folder of 'DirectoryName' is the directory is the one that is actually added to the project instead and the contents of the specified directory are temporarily/initialized in the listing.

![screenshot after closing-reopening - 2 of 2](https://cloud.githubusercontent.com/assets/8364502/11519027/74aaf35e-984b-11e5-85a7-417a28ceaba2.png)

Compare to using absolute paths:

```
atom.project.addpath("/home/user-name/DirectoryName")
```

The project explorer window has a folder with a name of 'DirectoryName' and all files.  Closing and re-opening (Tipping) the directory leaves the files unchanged.

Atom Version: 1.2.4
System: Ubuntu 14.04.3
### Done When:

Adding relative paths behaves similarly to adding absolute paths does in the project explorer window.

**Comment by thedaniel** [comment]
Thanks for the bug report. At the very least the API docs should say 'absolute path', but given that it's been ambiguous for this long making relative paths work is probably necessary.

**Comment by thedaniel** [comment]
Actually, this should require absolute paths only, because what the path is relative to is ambiguous in this context.
