### ISSUE TITLE
Unable to install packages message "CERT_UNTRUSTED"

### ISSUE THREAD

**Issue by r-richmond** [atom/atom#9900]
I noticed this morning that I was unable to install packages. 

I've already tried doing a clean install and reinstalling.

Windows 7
Version 1.2.4

![image](https://cloud.githubusercontent.com/assets/9246654/11520250/97037998-9856-11e5-9a5f-592968ad12b4.png)

**Comment by thedaniel** [comment]
- Are you on some kind of corporate proxy or ISP that intercepts your SSL traffic by any chance? 
- Have you ever been able to successfully install packages?

**Comment by r-richmond** [comment]
* Yes, is there someway to test this / What information could I provide to my sys admin to help diagnosis?  
* Yes, I was previously able to install packages. (As of a month ago?)

**Comment by r-richmond** [comment]
It is now magically fixed?... closing issue
