### ISSUE TITLE
installs in non standard location on windows. 

### ISSUE THREAD

**Issue by Sajaki** [atom/atom#9905]
hello, 

the atom installer put the executable in 
C:\Users\myusername\AppData\Local\atom\app-1.2.4
Is there is no way to put it in C:\Program Files or elsewhere ? 
I'll can't use this as it is now.

**Comment by thedaniel** [comment]
1.3 supports "portable mode" which should solve this problem: https://github.com/atom/atom/pull/8442

**Comment by 50Wliu** [comment]
You can also install to Program Files using `AtomSetup.exe --machine`.
