### ISSUE TITLE
Edit the last line of the file, and the file number is greater than the screen height, is not convenient, it is recommended to learn from the next text sublime

### ISSUE THREAD

**Issue by 120011676** [atom/atom#9908]
Edit the last line of the file, and the file number is greater than the screen height, is not convenient, it is recommended to learn from the next text sublime

**Comment by thedaniel** [comment]
I'm not sure what you mean by this - could you provide a screen shot or more clarification about the issue you're seeing?

**Comment by 120011676** [comment]
I'm sorry,English is not good.

![screenshot from 2015-12-02 22-09-13](https://cloud.githubusercontent.com/assets/1992933/11532944/1662fd08-9942-11e5-9f47-8a765151d3bc.png)
![Uploading Screenshot from 2015-12-02 22-09-13.png…]()

![screenshot from 2015-12-02 22-16-58](https://cloud.githubusercontent.com/assets/1992933/11533013/6efbf3f2-9942-11e5-8f4d-9e087300abfa.png)

**Comment by amytruong** [comment]
@120011676 I think I know what you're saying. The last line is always at the bottom of the screen and you do not like it. 
Do you want the screen to scroll up so you're not always typing at the bottom of the screen?

Please feel free to clarify if not. :smile:

**Comment by benogle** [comment]
There is a setting called `scroll past end` you can tick:

![screen shot 2015-12-02 at 10 35 33 am](https://cloud.githubusercontent.com/assets/69169/11540241/7abfa56a-98e0-11e5-9635-564d2fd56a2e.png)

**Comment by 120011676** [comment]
@amytruong Hi, it's you.:yes，smile:
@benogle Good，Thank you。

A child did not seriously listen, now English is not good ah。
How to learn English？

**Comment by mortenn** [comment]
I suspect this issue can be closed - it seems like "scroll past end" is what the op was looking for to me :)

**Comment by Ben3eeE** [comment]
Thanks @mortenn :bowing_man:

**Comment by ancienthero** [comment]
where is that setting?
