### ISSUE TITLE
Cannot delete file or folder from tree view (atom 1.3.0-beta6)

### ISSUE THREAD

**Issue by oh-ren** [atom/atom#9909]
See subject. Answering `Move to Trash` to the delete dialog results in nothing.

Works fine in atom 1.2.4.
Also 1.3.0-beta3 == no go.

Windows 7 (zip file install)

**Comment by glangford** [comment]
Electron windows v0.35.2 cannot use shell.moveItemToTrash
<https://github.com/atom/electron/issues/3656>

**Comment by oh-ren** [comment]
Thanks! :+1:

**Comment by 50Wliu** [comment]
@glangford 1.3.0 does not use Electron 0.35, however.  Was this also a problem on 0.34.x?

**Comment by oh-ren** [comment]
@50Wliu It was introduced in [Electron 0.34.3](https://github.com/atom/electron/releases/tag/v0.34.3) (which Atom 1.3.0 is based upon).

**Comment by 50Wliu** [comment]
Ok.  In that case can you please move this issue over to the atom/tree-view repo @oh-ren (since it's not fixed yet)?  Thanks!

**Comment by oh-ren** [comment]
@50Wliu It has nothing to to with atom/tree-view, as the issue seems to be atom/electron#3656?
(Or do you want it there as a reference?)

**Comment by 50Wliu** [comment]
Tree View is the only place that calls shell.moveItemToTrash I believe, right?

**Comment by oh-ren** [comment]
That seems to be right, done.
