### ISSUE TITLE
C++ indents removed in existing c++ files

### ISSUE THREAD

**Issue by shefmarkh** [atom/atom#9911]
Hello,

If I open a c++ file I have been using for some years now (in svn, but I am using a local copy) it looks fine in emacs (or "less" or "pico" etc). In atom many of the indents are removed, rendering the code very difficult to read. I have attached screenshots so you hopefully easily see the difference in display between emacs and atom.

I am using atom 1.2.4 in OS X 10.11.1

Thanks,

Mark

![screen shot 2015-12-02 at 14 36 57](https://cloud.githubusercontent.com/assets/12373167/11533546/39759de0-9902-11e5-98c2-dba6be948518.png)
![screen shot 2015-12-02 at 14 38 00](https://cloud.githubusercontent.com/assets/12373167/11533577/5a64f42e-9902-11e5-93bf-30cb610ee73e.png)

**Comment by thedaniel** [comment]
Do you perhaps have hard tabs set to display quite wide in emacs and quite narrow in atom?

**Comment by shefmarkh** [comment]
Hello,

So yes if I change the hard tab size from 2 to 8 the code indents look fine. However I don't want future indents, that I add, to be of size 8 so I don't want to have such a high setting.

In my emacs settings I see "standard indent" is 4, not 8. So naively I would think if I set hard tab size to 4 in atom the code should look identical in terms of indents (but it does not)?

Cheers,

Mark
