### ISSUE TITLE
Mac: Offer to move application to Applications folder

### ISSUE THREAD

**Issue by fulldecent** [atom/atom#9913]
![move](https://cloud.githubusercontent.com/assets/382183/11536223/6e7783ea-98e5-11e5-9839-791ac3401763.png)

This best practice is discussed here:
https://daringfireball.net/2009/09/how_should_mac_apps_be_distributed

And a simple implementation approach is discussed here:
https://github.com/potionfactory/LetsMove

**Comment by thedaniel** [comment]
Thanks for the feedback - I've added the appropriate labels.
