### ISSUE TITLE
Lag when typing return on a 3000 line php file, also seems related to the complexity of the code

### ISSUE THREAD

**Issue by Cipa** [atom/atom#9915]
Hi,

I have a file that is almost 3000 lines long and when I press return there is lag. When I press return 2 or more times I get proportionally more lag.
I can't post the test file but you can try this file

https://raw.githubusercontent.com/bcit-ci/CodeIgniter/develop/tests/codeigniter/libraries/Form_validation_test.php

and copy paste the code inside it until you get ~3000 or more lines of code. 

I also want t o mention that the lag also seems related to the complexity of the code, or maybe size, as a 3000 line of echo 'echo'; statements doesn't show a noticeable lag.

Thank you

**Comment by SuperuserMax** [comment]
Okay, I copied the file you suggested and repeated the code for a couple times so that it's about 3500 lines long.
When I press return there is absolutely no lag.
Might it be the case that you got some diverse hacks making syntax recognition code completion (ultimatively) slow?

**Comment by lee-dohm** [comment]
@Cipa Have you followed the suggestions in the [Debugging document](https://atom.io/docs/latest/hacking-atom-debugging)? Also, could you give the following information?

* Which version of Atom are you using?
* What OS and version are you running?
* Do you have [Emmet](https://atom.io/packages/emmet) installed?
* Can you reproduce the issue after completely exiting Atom and restarting using `atom --safe`?

**Comment by Cipa** [comment]
1.2.4
El Capitan
Yes

Seems like Emmet is the cause as it doesn't happen when it's disabled

**Comment by lee-dohm** [comment]
Thanks for the update @Cipa!
