### ISSUE TITLE
Keybindings shouldn't be case-sensitive

### ISSUE THREAD

**Issue by appsforartists** [atom/atom#9917]
## In Atom v1.2.4

If I add this to my `keymap`:

``` coffeescript
'html body atom-workspace.workspace *':
  'cmd-L': 'go-to-line:toggle'
```

and hit Cmd+L, it selects the line (the default behavior).  If I make the L lowercase:

``` coffeescript
'html body atom-workspace.workspace *':
  'cmd-l': 'go-to-line:toggle'
```

It works as expected (using `go-to-line` instead of `select-line`).

Keymaps should be case-insensitive.  Barring that, a warning should be thrown if a keymap contains non-lowercase keys.

Related: #9194

**Comment by Qix-** [comment]
Disagree. How do you handle cases of Shift? This would break ViM mode into ruins.

**Comment by appsforartists** [comment]
Other editors (like Sublime) use an explicit `shift-` modifier in their keymaps.

**Comment by lee-dohm** [comment]
Atom can use the explicit `shift` modifier too. These are equivalent: `cmd-L` and `cmd-shift-l`
