### ISSUE TITLE
auto-update should be configuable

### ISSUE THREAD

**Issue by zaczh** [atom/atom#9920]
Auto-update should not be enabled by default. When in China the download speed is very slow(the server maybe blocked). Sometimes the menu shows 'launch to install updates' but when I  relaunch Atom it failed to install the updates and the UI gets very weired(I got two atom interfaces and one have a blank screen which does not responds to any click events)
I think we should put auto-updating to a configurable option in `Preferencs`.

**Comment by 50Wliu** [comment]
An option to disable auto-updating is being discussed in #1882 - please subscribe there for updates!
