### ISSUE TITLE
Cannot install packages and possibly wrong error reported

### ISSUE THREAD

**Issue by louy2** [atom/atom#9925]
Log:
```
gyp info it worked if it ends with ok
gyp info using node-gyp@2.0.2
gyp info using node@0.10.40 | win32 | ia32
gyp http GET https://atom.io/download/atom-shell/v0.34.0/node-v0.34.0.tar.gz
gyp WARN install got an error, rolling back install
gyp
```

Looks to me that the GET failed (because, well, of Chinese GFW). I have a proxy but I don't know how to direct Atom through it, or how to inform Atom to use a mirror. Definitely related to #7575.

One solution would be bundle new node version into the installer. But I am not sure where are the other packages hosted. This might mean that all packages are blocked.

On the other hand, the error is reported as `Compiler tools not found` when I have both Python and VS installed.

**Comment by lee-dohm** [comment]
[Instructions on how to set proxy information](https://github.com/atom/apm#behind-a-firewall) can be found on the https://github.com/atom/apm repository. There are also multiple Issues in the apm repository that have suggestions if proxy settings aren't the only source of the problem.

Let us know if you need more help!

**Comment by louy2** [comment]
Thank you. Awaiting the first result through proxy. It's slow, but at least not failing yet.

Shall I open another issue for the wrong `Compiler tools not found` error?

**Comment by louy2** [comment]
Good news! Success through proxy.

**Comment by lee-dohm** [comment]
> Shall I open another issue for the wrong Compiler tools not found error?

I suspect that there already is an issue open for this. If you wouldn't mind checking the https://github.com/atom/apm repository? That's where the Issue should go.

**Comment by louy2** [comment]
I've done the searching but no similar issues came up. I'll post one there. Thanks for your help! On the other hand it's really a pity that `apm` repo seems to be blocked along with S3 Amazon.

**Comment by louy2** [comment]
Seems I was too quick to the conclusion. Just tried some other package and it installed successfully.
