### ISSUE TITLE
<script tag not detect close tag

### ISSUE THREAD

**Issue by PTKDev** [atom/atom#9932]
Hi!
I select with mouse `<script>` open tag but not appear underline on open/close tag: 
![Screenshot](http://openftp.ptkdev.it/Share/img/script_tag_atom.png)

With `<div>` and other tag underline appear:
![Screenshot](http://openftp.ptkdev.it/Share/img/script_tag_atom_work.png)

**Comment by lee-dohm** [comment]
This issue was moved to atom/bracket-matcher#193
