### ISSUE TITLE
Show user-made API documentation on mouse hover, like in Eclipse, NetBeans or IntelliJ/PHPStorm

### ISSUE THREAD

**Issue by lunarovic** [atom/atom#9936]
[There](https://atom.io/packages/api-docs) [are](https://atom.io/packages/quick-docs) [a lot of](https://atom.io/packages/live-doc-viewer) [Atom](https://atom.io/packages/quickdoc) [packages](https://atom.io/packages/devdocs) (← 5 links in there) which show API documentation in different ways, but none of them show user-made docs (Javadoc/JSDoc/PHPDoc format), only general language API documentation, for example from [DevDocs](http://devdocs.io/).

There are even packages like [jsdoc](https://atom.io/packages/jsdoc) or [docblockr](https://atom.io/packages/docblockr) which help the user by generating the documentation comments, but it seems that there are no packages which can read and display those comments on hover or click and there is no such functionality in Atom itself.

Example of the functionality in Eclipse:
![Eclipse Javadoc](https://cloud.githubusercontent.com/assets/2381553/21856834/97207daa-d823-11e6-916a-a28c850234fc.png)

**Comment by MoritzKn** [comment]
The package [ternjs](https://atom.io/packages/atom-ternjs) provides the command `atom-ternjs:documentation` to show the documentation for functions and variables and considers JSDoc comments for this too.

But it would be cool to have a package like [linter](https://github.com/steelbrain/linter) or [autocomplete-plus](https://github.com/atom/autocomplete-plus) with an API to show documentation from different language specific provider.

**Comment by joebri** [comment]
:+1:  for this request.

**Comment by eddydarell** [comment]
I have also been looking for a similar functionality and just realized that there is one very well implemented in Visual Studio Code. So as a Atom user, I'll 👍 for this request.

**Comment by kujovic** [comment]
@eddydarell How do you do that in VS Code? I thought that functionality didn't exist there either.

**Comment by eddydarell** [comment]
@kujovic honestly, I have no idea. I just realized that I got a bubble with my self-written JSDoc block style comments whenever I hover a method or its parameters. As a matter of fact, I get it whenever I hover any method, variable, constant or parameter. 
I don't recall installing any package for that so I assume it is something preinstalled.

**Comment by eddydarell** [comment]
And I believe it is safe to mention that I have had this only with JavaScript so far.

**Comment by thematver** [comment]
I'd love to see this in Atom too.
