### ISSUE TITLE
Atom won't write ' [ ' 

### ISSUE THREAD

**Issue by xPhentom** [atom/atom#9938]
For some reason, Atom won't write the symbol ' [ '

**Comment by mnquintana** [comment]
What keyboard layout are you using?

**Comment by xPhentom** [comment]
Belgian period layout -- AZERTY

**Comment by mnquintana** [comment]
Ah sorry about this - this looks like another symptom of https://github.com/atom/atom-keymap/issues/37. Feel free to subscribe there for updates.

**Comment by xPhentom** [comment]
Thanks
