### ISSUE TITLE
On close, "don't save all"

### ISSUE THREAD

**Issue by drj-io** [atom/atom#9957]
<img width="490" alt="rsdi5yf" src="https://cloud.githubusercontent.com/assets/1038121/11611983/7c775ade-9b9b-11e5-9405-30f24ba4cb43.png">

Would be cool if there was an "apply to all" here.  Sometimes my mounted share gets disconnected and Atom thinks all the files need to be "saved" because they're no longer there.

**Comment by Dayjo** [comment]
+1 for this, it's frustrating if you need to quit Atom and have several projects open with several files in - not being able to bulk choose and having to repeatedly click Don't Save.

**Comment by Yajo** [comment]
No need to quit, just switch a git branch and close tabs from the older branch. If you had 20 tabs, it's 20 clicks. :disappointed:

**Comment by hultberg** [comment]
@Dayjo @Yajo You should try the [file-watcher](https://atom.io/packages/file-watcher) package.

**Comment by Ben3eeE** [comment]
https://github.com/atom/atom/issues/7906?

**Comment by lee-dohm** [comment]
@Ben3eeE That one was closed in favor of this one.

**Comment by jontayesp** [comment]
Before you click "don't save all", it would be cool to see a scrolling list of all the unsaved files in your workspace. That way you can quickly check to make sure you don't have any open files you really did want to save (but 99% of the time you really want everything unsaved and just exit, in the case of a branch switch, etc).

@lee-dohm is there interest in getting this feature addressed?

**Comment by Dayjo** [comment]
I don't think this is stale, this is still an ongoing issue and would be great if it could be implemented!

**Comment by phil-r** [comment]
Just had to click it almost a hundred times after I checked out a different branch

**Comment by Jones-S** [comment]
I still see this as an issue. Whenever I switch git branches I have click my index finger into crazyness.
It would be great if this feature was implemented.
Using Mac Os Mojave with newest Atom.
Steps to reproduce. Make a new branch, create 10 files with random content. Save them.
Switch branch (where the files don't exist) and use command `close all Tabs`.. voila
