### ISSUE TITLE
Unable to find a valid app

### ISSUE THREAD

**Issue by marsoln** [atom/atom#9959]
![image](https://cloud.githubusercontent.com/assets/7898688/11612128/51a61592-9c28-11e5-9279-538e2933bbab.png)

win10 x64

**Comment by lee-dohm** [comment]
Can you give a little more information?

* How did you install the application?
* How did you download the application?
* How did you launch the application?
* Is this your first time running the application?

**Comment by marsoln** [comment]
I downloaded the patch from Atom.io,
and followed the step to install it on Windows 10 Pro.
And then installed two package,first one is "activate-power-mode" and the second i forgot the name, some kind of Theme.
It runs well,but the next day i opened it, then it occured this error.

**Comment by marsoln** [comment]
Today i reinstall atom, and everything goes fine.
