### ISSUE TITLE
Boot up Error for Atom 1.2.4 for Windows 10

### ISSUE THREAD

**Issue by Yathushan** [atom/atom#9960]
**Reproduction Steps:**

1. Open up Atom
2. Watch error

**Expected behavior:**

Expected the Editor to open with a blank page to insert code.

**Observed behavior:**

Editor opens and only developer tools appears at the bottom highlighting an error.

**Screenshots and GIFs**

![image](https://cloud.githubusercontent.com/assets/335441/11613419/70416bd4-9c17-11e5-83a1-1415280bb172.png)

**Atom version:**  1.2.4
**OS and version:** Window 10

**Installed packages:**

meteor-api
meteor-helper

**Additional information:**

* Problem can be reproduced in safe mode: Yes

* Problem started happening recently, didn't happen in an older version of Atom: Yes - Just using started this version. But it is reproduced with Verion 1.3.0 - beta 6 and 1.2.3

* Problem can be reliably reproduced, doesn't happen randomly: Yes

* Problem happens with all files and projects, not only some files or projects: Yes

**Comment by lee-dohm** [comment]
Most of the time this happens on Windows when your `$HOME\.atom` directory is inaccessible for some reason ... typically a permissions issue. Have you tried double checking that directory?

**Comment by Yathushan** [comment]
Hi Lee,

So I located the folder and found that it was accessible.

When I renamed the folder and reinstalled the atom application, it was back to normal without any addons installed. I think the result might have been some corrupted config files which were not removed.

**Comment by lee-dohm** [comment]
Great! So is this fixed then?
