### ISSUE TITLE
Golang syntax highlighting multiline strings in var block not highlighted

### ISSUE THREAD

**Issue by zazab** [atom/atom#9964]
If you have a multiline string in `var` section, it is not highlighted as string. Here is screenshot  with simple example:

![strings_bug](https://cloud.githubusercontent.com/assets/2859912/11618687/fbd17380-9cbf-11e5-83b9-40593f1a146a.png)

Scopes shown for every `string` entry from top to bottom. This bug reproduced with all string delimeters (`'`, `"`, `)

Atom version: 1.2.4

**Comment by 50Wliu** [comment]
This has already been fixed and should be available in Atom 1.3.0.
