### ISSUE TITLE
Cursor doesn't jump to line without column number

### ISSUE THREAD

**Issue by maahd** [atom/atom#9967]
Ctrl + G: "Enter a line row:column to go to". Ideally if I don't enter a column number and only a row number, it should go to the first column. But it doesn't. This is a usability issue and is up to the Atom team to decide. I just think it's one less keystroke if it's implemented. I say one keystroke, since entering a colon without the column number works as well. I'm using V 1.2.0 on Ubuntu 14.04 LTS.

**Comment by 50Wliu** [comment]
Really?  It does for me.  Does this still happen in safe mode (`atom --safe`)?

**Comment by maahd** [comment]
So going in safe mode solves the problem. And now it's not happening without safe mode either...

**Comment by 50Wliu** [comment]
Well, that's good to know.  If it happens again please comment here so that we can reopen this issue.
