### ISSUE TITLE
SuSE 13.1 / KDE Atom Window is always on Top

### ISSUE THREAD

**Issue by oers** [atom/atom#9969]
I just installed 1.2.4 via rpm in my Suse 13.1 Installation.
This error also occurs in the current beta-version.

The Atom-Window is always "on top" and hides everything benath it. Klicking on other windows / switching to other screens will always have the atom window on top.
Only way to minimize it is via the standard minimize controls, but the normal window behavior on loosing focus is not working.

Window has Focus:
![normal](https://cloud.githubusercontent.com/assets/1115563/11650872/d7d3ebe8-9d8c-11e5-8780-9e90393a1b8a.PNG)

Other Window has Focus. Atom Editor is "on top" and has lost the windows decoration
![otherwindow](https://cloud.githubusercontent.com/assets/1115563/11650877/db7ee7ac-9d8c-11e5-9131-beec8885dd29.PNG)

The most annoying part is, that the main window also hides all other dialogs. And often you don't know why the gui is not reacting:
After moving away the main Window:
![image](https://cloud.githubusercontent.com/assets/1115563/11650933/62adebc4-9d8d-11e5-8f68-6c6480da401d.png)

**Comment by oers** [comment]
I could not reproduce this in any other linux distribution.
Ubuntu, Suse 13.2, Suse 42. all worked fine.
Closing this issue.

**Comment by JaneSmith** [comment]
I have this issue on Ubuntu 14.04 LTS running inside VirtualBox.

**Comment by JaneSmith** [comment]
I get this issue on Ubuntu 14.04 LTS running inside VirtualBox.

**Comment by paras20xx** [comment]
I see this same issue on a fresh installation of Ubuntu 16.04 (on VirtualBox v5.0.20 with extension pack and guestbox additions)

**Comment by tarach** [comment]
I had exactly the same problem.
 - Virtualbox 5.0.20 r 106931
 - Linux 3.16.0-4-amd64 #1 SMP Debian 3.16.7-ckt25-2 (2016-04-08) x86_64 GNU/Linux
 - Atom 1.7.3

Disabling ( untick ) Guest Settings -> Display -> Enable 3D Acceleration 
Solved the problem for me and Atom isn't "Always on top" anymore.

~ thanks

**Comment by hoto** [comment]
For a Vagrant/VirtualBox powered GUI machine workaround is to write this to `Vagrantfile`  

```ruby
vb.customize ["modifyvm", :id, "--accelerate3d", "off"]
```
