### ISSUE TITLE
Won't run after a "Not responding" on Win7

### ISSUE THREAD

**Issue by Errvald** [atom/atom#9973]
After an hour or two Atom goes blank "Not responding". It takes a system reboot to run it again.
I've noticed there's at least 2 ``Atom.exe`` processes still running in the Task manager which won't end.

**Comment by lee-dohm** [comment]
Have you followed the suggestions in the [Debugging document](https://atom.io/docs/latest/hacking-atom-debugging)? Also, could you give the following information?

* Which version of Atom are you using?
* Do you have [Emmet](https://atom.io/packages/emmet) installed?
* Can you reproduce the issue after completely exiting Atom and restarting using `atom --safe`?

**Comment by fsnx** [comment]
That's exactly what is happening to me, i can't run Atom again without a reboot.

* Atom version 1.3.2.
* Emmet installed (but i don't think it matters, this happened before without Emmet).
* Will test later if it occur in the safe mode (can't reboot now).

**Comment by damieng** [comment]
Not enough information and reporter is not providing any additional information.
