### ISSUE TITLE
Update all bundled packages to use new package.json fields, so their main modules can be required later

### ISSUE THREAD

**Issue by maxbrunsfeld** [atom/atom#9974]
Depends on https://github.com/atom/atom/pull/9975.
Don't merge these PRs until 1.4.0 is released.
Packages with ~~slashes~~ through them require no changes.

* [x] one-dark-ui https://github.com/atom/one-dark-ui/pull/113
* [x] one-light-ui https://github.com/atom/one-light-ui/pull/48
* [x] about ~~https://github.com/atom/about/pull/6~~, https://github.com/atom/about/pull/13
* [x] archive-view https://github.com/atom/archive-view/pull/32
* ~~autocomplete-atom-api~~
* ~~autocomplete-css~~
* ~~autocomplete-html~~
* [x] autocomplete-plus https://github.com/atom/autocomplete-plus/pull/637
* ~~autocomplete-snippets~~
* ~~autoflow~~
* [x] autosave https://github.com/atom/autosave/pull/56
* ~~background-tips~~
* ~~bookmarks~~
* [x] bracket-matcher https://github.com/atom/bracket-matcher/pull/197
* command-palette
* [x] deprecation-cop ~~https://github.com/atom/deprecation-cop/pull/65~~ https://github.com/atom/deprecation-cop/pull/67
* ~~dev-live-reload~~
* ~~encoding-selector~~
* ~~exception-reporting~~
* [x] find-and-replace https://github.com/atom/find-and-replace/pull/617
* [x] fuzzy-finder https://github.com/atom/fuzzy-finder/pull/160
* [x] git-diff https://github.com/atom/git-diff/pull/81
* ~~go-to-line~~
* [x] grammar-selector https://github.com/atom/grammar-selector/pull/29
* ~~image-view~~
* [x] incompatible-packages ~~https://github.com/atom/incompatible-packages/pull/11~~ https://github.com/atom/incompatible-packages/pull/12
* ~~keybinding-resolver~~
* [x] line-ending-selector https://github.com/atom/line-ending-selector/pull/17
* ~~link~~
* [x] markdown-preview ~~https://github.com/atom/markdown-preview/pull/349~~ https://github.com/atom/markdown-preview/pull/367
* ~~metrics~~
* [x] notifications https://github.com/atom/notifications/pull/105
* [x] open-on-github https://github.com/atom/open-on-github/pull/59
* [x] package-generator https://github.com/atom/package-generator/pull/37
* [x] settings-view https://github.com/atom/settings-view/pull/731
* ~~snippets~~
* [x] spell-check https://github.com/atom/spell-check/pull/112
* [x] status-bar https://github.com/atom/status-bar/pull/121
* [x] styleguide https://github.com/atom/styleguide/pull/34
* [x] symbols-view https://github.com/atom/symbols-view/pull/151
* [x] tabs https://github.com/atom/tabs/pull/260
* [x] timecop https://github.com/atom/timecop/pull/15
* [x] tree-view https://github.com/atom/tree-view/pull/731
* ~~update-package-dependencies~~
* [x] welcome https://github.com/atom/welcome/pull/45
* [x] whitespace https://github.com/atom/whitespace/pull/107
* ~~wrap-guide~~

**Comment by as-cii** [comment]
Great work, @maxbrunsfeld. Thanks so much for addressing this :sparkles:

**Comment by jeancroy** [comment]
command-palette currently have one [config](https://github.com/atom/command-palette/blob/master/lib/command-palette-view.coffee#L9) item.

Autocomplete plus [alternate scoring](https://github.com/atom/autocomplete-plus/pull/637/files#diff-b9cfc7f2cdf78a7f4b91a753d10865a2R179) may change in the [near future](https://github.com/atom/fuzzy-finder/pull/159#issuecomment-164914709)

**Comment by maxbrunsfeld** [comment]
> command-palette currently have one config item.

Thanks for catching that @jeancroy!
