### ISSUE TITLE
Opening files with different encoding than UTF-8 is really slow

### ISSUE THREAD

**Issue by krial057** [atom/atom#9979]
Hello,

I have a file that has characters different than UTF-8. It takes really long to change the encoding of the file to the correct one. When I chage the default encoding in Atom, opening such a file takes very long too. 

**Steps to reproduce**
 * Download the following file [test.txt](https://github.com/atom/atom/files/55197/test.txt)
 * Set the default encoding of Atom to Western(Windows 1252)
 * Open the file you just downloaded in Atom

Opening will take pretty long(on my machine it takes around 10 seconds)
When changing the default encoding back to UTF-8 in Atom and opening the file, it loads very fast.

**Version of Atom I tried that were affected**
 * 1.3.0 beta6
 * 1.2.4

**Operating Systems tested on**
 * Windows 7
 * Windows 10

**Comment by nathansobo** [comment]
@as-cii Does atom/text-buffer#119 close this?

**Comment by as-cii** [comment]
@nathansobo: yes, I just bumped `text-buffer` to the latest version on master (b3b8b8d) and this should be fast now. :racehorse: 

We will release it in Atom v1.4.0 and v1.4.0-beta0.. Thanks for the report, @krial057!
