### ISSUE TITLE
After upgrade to 1.2.4, Window menu no longer lists open windows

### ISSUE THREAD

**Issue by ttrahan** [atom/atom#9983]
Running Atom on a MacBook Air running Yosemite 10.10.5.

After upgrading the core package to 1.2.4, the Window menu no longer contains a list of the open windows.  The list of open windows also no longer appears when selecting the Atom icon from the Dock.  If a window is minimized to the Dock, it is no longer accessible.

I've taken the following screenshots with 4 Atom windows open:

Missing list of open windows from the Window menu:
![image](https://cloud.githubusercontent.com/assets/4467650/11672016/67faeff8-9dc1-11e5-9762-9724a129a831.png)

Missing list of open windows from the Dock icon:
![image](https://cloud.githubusercontent.com/assets/4467650/11671996/427e6304-9dc1-11e5-959d-cb9fa2ea8455.png)

**Comment by 50Wliu** [comment]
This has already been fixed in the 1.3.0 betas.

**Comment by ttrahan** [comment]
Confirmed that this works in 1.3.0 beta.  Thanks.
