### ISSUE TITLE
Creating a new Atom window on Mac crashes Atom

### ISSUE THREAD

**Issue by elebumm** [atom/atom#9986]
Whenever I do a new window for Atom, it crashes the whole atom session. I am currently using El Capitan 10.11.1

**Comment by ihatetoregister** [comment]
Could not reproduce (using ⇧⌘N) on El Cap 10.11.2 and Atom 1.2.4.

**Comment by mnquintana** [comment]
Can you reproduce this in safe mode? (`atom --safe`)
