### ISSUE TITLE
Untitled buffers don't save language state

### ISSUE THREAD

**Issue by 50Wliu** [atom/atom#9992]
This is a pretty common usage scenario for me as I open a temporary tab in language repos to test out changes that I make:
1. Open a new untitled buffer
2. Set the language to anything other than Plain Text (eg Java)
3. write some text
4. Reload Atom

**Expected**: Language is still Java
**Actual**: Language is reset to Plain Text

Atom 1.4.0-dev-77a5409 **non safe-mode**, Windows 10 x64

/cc @as-cii

**Comment by as-cii** [comment]
Thanks, @50Wliu!

@atom/feedback: thoughts?

**Comment by lee-dohm** [comment]
I agree, untitled buffers should save the language state.

**Comment by joshaber** [comment]
Yup, I agree too :+1:

**Comment by mnquintana** [comment]
Yup, definitely on board with this :+1:
